### PR TITLE
K8SPSMDB-551: Don't step down and restart if primary node is external

### PR DESCRIPTION
**Pull request by egegunes**

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Review by defbin — APPROVED** [review]
lgtm

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | failed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| upgrade | passed |
| liveness | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| pitr | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/758/commits/63a1026dbd2b60461adcecfc35f3085a3591bc7d
image: `perconalab/percona-server-mongodb-operator:PR-758-63a1026d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-chaos | passed |
| security-context | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/758/commits/63a1026dbd2b60461adcecfc35f3085a3591bc7d
image: `perconalab/percona-server-mongodb-operator:PR-758-63a1026d`

**Review by nonemax — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/758/commits/7bafa79fc8132ea84003eaf35c8f6cf5e7347dc0
image: `perconalab/percona-server-mongodb-operator:PR-758-7bafa79f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| scaling | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| security-context | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/758/commits/7bafa79fc8132ea84003eaf35c8f6cf5e7347dc0
image: `perconalab/percona-server-mongodb-operator:PR-758-7bafa79f`

**Pull request merged**
