### PR TITLE
use github.com/percona/percona-backup-mongodb v1.6.1

### PR DESCRIPTION
**Pull request by defbin**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/908e26a8886c9b6fd3cef59537849377b4d916c3
image: `perconalab/percona-server-mongodb-operator:PR-820-908e26a8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| storage | passed |
| scaling | passed |
| self-healing | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| scheduled-backup | failed |
| demand-backup-sharded | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/908e26a8886c9b6fd3cef59537849377b4d916c3
image: `perconalab/percona-server-mongodb-operator:PR-820-908e26a8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/536822359c13a0f31ce47aeb57991b22894603a5
image: `perconalab/percona-server-mongodb-operator:PR-820-53682235`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-chaos | passed |
| security-context | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| scheduled-backup | failed |
| demand-backup-sharded | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/536822359c13a0f31ce47aeb57991b22894603a5
image: `perconalab/percona-server-mongodb-operator:PR-820-53682235`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/7f549c6d4b21d5feb53844fe43f9893cd3394c65
image: `perconalab/percona-server-mongodb-operator:PR-820-7f549c6d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| one-pod | failed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| scheduled-backup | failed |
| demand-backup-sharded | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/7f549c6d4b21d5feb53844fe43f9893cd3394c65
image: `perconalab/percona-server-mongodb-operator:PR-820-7f549c6d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | failed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/b01b8cf50fc859c000a10652d51428a524783d7b
image: `perconalab/percona-server-mongodb-operator:PR-820-b01b8cf5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| monitoring-2-0 | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| scheduled-backup | failed |
| demand-backup-sharded | failed |
| upgrade | failed |
| smart-update | passed |
| version-service | passed |
| users | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/c7e7410634fd24f79b3294bf3bae2e2bc00caaf4
image: `perconalab/percona-server-mongodb-operator:PR-820-c7e74106`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| demand-backup | failed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/93854e7b0f7ebec8bc7796210723d247a59bc4c7
image: `perconalab/percona-server-mongodb-operator:PR-820-93854e7b`

**Review by dAdAbird — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | failed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/c60002aec0506c48d1a8d00951f38f45e328ffe8
image: `perconalab/percona-server-mongodb-operator:PR-820-c60002ae`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/820/commits/c60002aec0506c48d1a8d00951f38f45e328ffe8
image: `perconalab/percona-server-mongodb-operator:PR-820-c60002ae`

**Review by delgod — APPROVED** [review]

**Pull request merged**
