### PR TITLE
K8SPSMDB-548: Add mongo client timeouts for healthcheck

### PR DESCRIPTION
**Pull request by egegunes**

### CODE REVIEW

**Review by defbin — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| init-deploy | failed |
| storage | failed |
| upgrade-consistency | failed |
| monitoring-2-0 | failed |
| self-healing | passed |
| limits | failed |
| scaling | passed |
| demand-backup | failed |
| security-context | failed |
| self-healing-chaos | passed |
| arbiter | failed |
| scheduled-backup | failed |
| rs-shard-migration | failed |
| service-per-pod | failed |
| demand-backup-sharded | failed |
| operator-self-healing | passed |
| liveness | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| smart-update | failed |
| upgrade-sharded | passed |
| version-service | failed |
| pitr | failed |
| users | passed |
| pitr-sharded | failed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/7051514722fcc7c4f92af71ac4d1b6b684a9620d
image: `perconalab/percona-server-mongodb-operator:PR-766-70515147`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/afc1adbfdab9f048fda14fc7251875aef5d62165
image: `perconalab/percona-server-mongodb-operator:PR-766-afc1adbf`

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| upgrade | passed |
| service-per-pod | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| liveness | passed |
| smart-update | passed |
| pitr | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/afc1adbfdab9f048fda14fc7251875aef5d62165
image: `perconalab/percona-server-mongodb-operator:PR-766-afc1adbf`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-chaos | passed |
| security-context | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | failed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/afc1adbfdab9f048fda14fc7251875aef5d62165
image: `perconalab/percona-server-mongodb-operator:PR-766-afc1adbf`

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | failed |
| scaling | passed |
| security-context | passed |
| scheduled-backup | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| demand-backup-sharded | failed |
| service-per-pod | passed |
| operator-self-healing | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| users | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/bedf56adf06fa08635e2b90731768431a65dcd10
image: `perconalab/percona-server-mongodb-operator:PR-766-bedf56ad`

**Review by nonemax — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | failed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| upgrade | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| smart-update | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/1398cd36dd130d9c37ad1f02b4189300f24042d4
image: `perconalab/percona-server-mongodb-operator:PR-766-1398cd36`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/04066e9bfba5cefd61bca181b00ab51ece571d5f
image: `perconalab/percona-server-mongodb-operator:PR-766-04066e9b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| limits | passed |
| scaling | passed |
| self-healing-chaos | passed |
| security-context | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| operator-self-healing-chaos | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/3e4aeb376c1b7d0cf25db946ff03010788bc1825
image: `perconalab/percona-server-mongodb-operator:PR-766-3e4aeb37`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/3c06f1f00f8e578e409d1afe87acf2340936460b
image: `perconalab/percona-server-mongodb-operator:PR-766-3c06f1f0`

**Review by hors — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| init-deploy | failed |
| one-pod | failed |
| upgrade-consistency | failed |
| monitoring-2-0 | failed |
| limits | failed |
| demand-backup | failed |
| self-healing | failed |
| scaling | failed |
| scheduled-backup | failed |
| self-healing-chaos | failed |
| arbiter | failed |
| operator-self-healing | failed |
| security-context | failed |
| demand-backup-sharded | failed |
| service-per-pod | failed |
| operator-self-healing-chaos | failed |
| rs-shard-migration | failed |
| upgrade | failed |
| liveness | failed |
| smart-update | failed |
| upgrade-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/52f623402358ec1ae176cb78a379a1153e7852f2
image: `perconalab/percona-server-mongodb-operator:PR-766-52f62340`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| upgrade-sharded | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/766/commits/52f623402358ec1ae176cb78a379a1153e7852f2
image: `perconalab/percona-server-mongodb-operator:PR-766-52f62340`

**Pull request merged**
