### PR TITLE
CLOUD-622 add examples of architecture decision records

### PR DESCRIPTION
**Pull request by hors**
[CLOUD-622](https://jira.percona.com/browse/CLOUD-622) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| users | passed |
| data-sharded | passed |
| upgrade | passed |
| upgrade-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/660/commits/7520c30236c48161d11ce07b492889342dd5b72f
image: `perconalab/percona-server-mongodb-operator:PR-660-7520c302`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/660/commits/6ce0f0637d9c7f29202c712946e32e4386f87235
image: `perconalab/percona-server-mongodb-operator:PR-660-6ce0f063`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| upgrade | passed |
| version-service | passed |
| upgrade-sharded | passed |
| users | failed |
| pitr | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/660/commits/cf74b86455b19b773243a5d52db20b3b7f21bdee
image: `perconalab/percona-server-mongodb-operator:PR-660-cf74b864`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| one-pod | passed |
| security-context | passed |
| monitoring-2-0 | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| storage | passed |
| smart-update | passed |
| self-healing | passed |
| version-service | passed |
| operator-self-healing | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/660/commits/cf74b86455b19b773243a5d52db20b3b7f21bdee
image: `perconalab/percona-server-mongodb-operator:PR-660-cf74b864`

**Pull request merged**
