### PR TITLE
K8SPSMDB-488 - Preparation after 1.9.0 release

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPSMDB-488](https://jira.percona.com/browse/K8SPSMDB-488) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | failed |
| operator-self-healing | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| pitr | passed |
| pitr-sharded | failed |
| smart-update | failed |
| version-service | failed |
| users | failed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/722/commits/91e4ce8ef4b3c4e7b93c8f1f7422573dbdd5f953
image: `perconalab/percona-server-mongodb-operator:PR-722-91e4ce8e`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| version-service | passed |
| operator-self-healing-chaos | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/722/commits/472e5b66c01245b7bc4e025563b05b4c997d613c
image: `perconalab/percona-server-mongodb-operator:PR-722-472e5b66`

**Review by delgod — APPROVED** [review]

**Review by hors — APPROVED** [review]
@tplavcic  should we update bundle.yaml?

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| scheduled-backup | passed |
| liveness | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/722/commits/eb4d1ba33a9ee7be3a3dd21129ca8c3b4f38894d
image: `perconalab/percona-server-mongodb-operator:PR-722-eb4d1ba3`

**Pull request merged**
