### PR TITLE
K8SPSMDB-293: Use same version of init image as cr version

### PR DESCRIPTION
**Pull request by qJkee**
[K8SPSMDB-293](https://jira.percona.com/browse/K8SPSMDB-293)

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | failed |
| one-pod | failed |
| upgrade | failed |
| limits | failed |
| self-healing | failed |
| monitoring | failed |
| scaling | failed |
| operator-self-healing | failed |
| monitoring-2-0 | failed |
| security-context | failed |
| arbiter | failed |
| service-per-pod | failed |
| liveness | failed |

**Comment by tplavcic** [comment]
I have a problem with this, if nothing then for testing stuff, there's a difference between how PXC handles this and how PSMDB handles this, if I patch PSMDB cluster like:
```
kubectl patch psmdb my-cluster-name --type=merge --patch '{
   "spec": {
       "crVersion": "1.6.0",
       "image": "percona/percona-server-mongodb:4.2.8-8",
       "backup": { "image": "perconalab/percona-server-mongodb-operator:master-backup" },
       "pmm": { "image": "perconalab/percona-server-mongodb-operator:master-pmm" }
   }}'
```
the init container that it will try to use is `perconalab/percona-server-mongodb-operator:1.6.0`
but for PXC if I patch it like:
```
kubectl patch pxc cluster1 --type=merge --patch '{
   "spec": {
       "crVersion": "1.7.0",
       "pxc":{ "image": "percona/percona-xtradb-cluster:8.0.20-11.3" },
       "proxysql": { "image": "perconalab/percona-xtradb-cluster-operator:master-proxysql" },
       "haproxy": { "image": "perconalab/percona-xtradb-cluster-operator:master-haproxy" },
       "backup":   { "image": "perconalab/percona-xtradb-cluster-operator:master-pxc8.0-backup" },
       "pmm":      { "image": "percona/percona-xtradb-cluster-operator:1.4.0-pmm" }
   }}'
```
the init container it will use is:
```
Init Containers:
  pxc-init:
    Container ID:
    Image:         perconalab/percona-xtradb-cluster-operator:master
```
so you can see it did not use `perconalab/percona-xtradb-cluster-operator:1.7.0` as init image.
If nothing else it means that for running the tests we will need to push PSMDB images to perconalab repo for unreleased versions while for PXC we don't need to do that - makes it very confusing.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | failed |
| one-pod | failed |
| upgrade | failed |
| limits | failed |
| self-healing | failed |
| monitoring | failed |
| scaling | failed |
| operator-self-healing | failed |
| monitoring-2-0 | failed |
| security-context | failed |
| arbiter | failed |
| service-per-pod | failed |
| liveness | failed |

**Comment by tplavcic** [comment]
Shouldn't the logic be use the operator image as init image UNLESS the version is different and then use image+cr.Version?
From what I see PXC code does that: https://github.com/percona/percona-xtradb-cluster-operator/commit/22eb15412907bc76370fa0e15ba7c28bc6316062#diff-3fa3ab828e096d1652e014a7a6325074f9cfbecf9894d9ca7e609600cfc9ccd0R545-R546

**Review by tplavcic — CHANGES_REQUESTED** [review]
needs to be the same as PXC

**Review by tplavcic — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade | passed |
| monitoring | passed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | failed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| arbiter | failed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |
| users | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | failed |
| monitoring-2-0 | passed |
| scaling | passed |
| operator-self-healing | passed |
| demand-backup | passed |
| arbiter | passed |
| security-context | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |
| users | failed |

**Pull request merged**
