### PR TITLE
K8SPSMDB-520: add volumes and PVC for sidecars

### PR DESCRIPTION
**Pull request by defbin**

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| one-pod | failed |
| storage | passed |
| upgrade-consistency | failed |
| self-healing | passed |
| demand-backup | failed |
| limits | failed |
| monitoring-2-0 | failed |
| scaling | passed |
| scheduled-backup | failed |
| security-context | failed |
| self-healing-chaos | passed |
| demand-backup-sharded | failed |
| arbiter | passed |
| rs-shard-migration | failed |
| operator-self-healing | passed |
| upgrade | failed |
| service-per-pod | failed |
| operator-self-healing-chaos | passed |
| liveness | failed |
| smart-update | failed |
| version-service | failed |
| users | passed |
| data-sharded | passed |
| non-voting | failed |
| upgrade-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/781/commits/b551a3d5286dd250904b2ca4199525f2a074cc1f
image: `perconalab/percona-server-mongodb-operator:PR-781-b551a3d5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/781/commits/49b404df46bc8b6fe542adb4ec2f140fa8864e38
image: `perconalab/percona-server-mongodb-operator:PR-781-49b404df`

**Review by egegunes — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| security-context | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/781/commits/49b404df46bc8b6fe542adb4ec2f140fa8864e38
image: `perconalab/percona-server-mongodb-operator:PR-781-49b404df`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| storage | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/781/commits/49b404df46bc8b6fe542adb4ec2f140fa8864e38
image: `perconalab/percona-server-mongodb-operator:PR-781-49b404df`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| monitoring-2-0 | passed |
| limits | passed |
| self-healing | passed |
| arbiter | passed |
| scaling | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| security-context | passed |
| operator-self-healing | passed |
| liveness | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/781/commits/49b404df46bc8b6fe542adb4ec2f140fa8864e38
image: `perconalab/percona-server-mongodb-operator:PR-781-49b404df`

**Review by qJkee — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Pull request merged**
