### PR TITLE
K8SPSMDB-502 Replace deprecated Kubernetes APIs

### PR DESCRIPTION
**Pull request by delgod**
[K8SPSMDB-502](https://jira.percona.com/browse/K8SPSMDB-502) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by hors — COMMENTED** [review]
@delgod we need to update bundl.yaml too

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| init-deploy | failed |
| one-pod | failed |
| upgrade-consistency | failed |
| limits | failed |
| demand-backup | failed |
| monitoring-2-0 | failed |
| self-healing | failed |
| scaling | failed |
| self-healing-chaos | failed |
| scheduled-backup | failed |
| security-context | failed |
| operator-self-healing | failed |
| arbiter | failed |
| rs-shard-migration | failed |
| demand-backup-sharded | failed |
| operator-self-healing-chaos | failed |
| service-per-pod | failed |
| upgrade | failed |
| liveness | failed |
| smart-update | failed |
| version-service | failed |
| upgrade-sharded | failed |
| users | failed |
| data-sharded | failed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/a2e423f748dcaf34d6cbc9e2c545304e251264a7
image: `perconalab/percona-server-mongodb-operator:PR-714-a2e423f7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| one-pod | failed |
| init-deploy | failed |
| upgrade-consistency | failed |
| limits | failed |
| demand-backup | failed |
| monitoring-2-0 | failed |
| self-healing | failed |
| scaling | failed |
| self-healing-chaos | failed |
| scheduled-backup | failed |
| security-context | failed |
| operator-self-healing | failed |
| arbiter | failed |
| rs-shard-migration | failed |
| demand-backup-sharded | failed |
| operator-self-healing-chaos | failed |
| service-per-pod | failed |
| upgrade | failed |
| liveness | failed |
| smart-update | failed |
| version-service | failed |
| upgrade-sharded | failed |
| users | failed |
| data-sharded | failed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/f785be3d76a49cca5edeb8db4fb0dd6f4edcca3f
image: `perconalab/percona-server-mongodb-operator:PR-714-f785be3d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | failed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| upgrade | failed |
| operator-self-healing-chaos | passed |
| liveness | passed |
| upgrade-sharded | failed |
| smart-update | passed |
| version-service | failed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/1d0176630cb2b3dd2840354e7e277cc1e746c335
image: `perconalab/percona-server-mongodb-operator:PR-714-1d017663`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | failed |
| init-deploy | failed |
| upgrade-consistency | passed |
| storage | failed |
| demand-backup | failed |
| monitoring-2-0 | failed |
| limits | passed |
| self-healing | failed |
| scaling | failed |
| scheduled-backup | failed |
| security-context | failed |
| arbiter | failed |
| self-healing-chaos | failed |
| demand-backup-sharded | failed |
| service-per-pod | failed |
| liveness | failed |
| operator-self-healing | failed |
| rs-shard-migration | failed |
| upgrade | failed |
| upgrade-sharded | failed |
| pitr | passed |
| smart-update | failed |
| operator-self-healing-chaos | failed |
| pitr-sharded | passed |
| version-service | failed |
| users | failed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/a8330bc5d21e4a94e2e78b18c11a9eaac9826a07
image: `perconalab/percona-server-mongodb-operator:PR-714-a8330bc5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| self-healing-chaos | passed |
| security-context | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | failed |
| upgrade-sharded | failed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |
| users | passed |
| data-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/1d0176630cb2b3dd2840354e7e277cc1e746c335
image: `perconalab/percona-server-mongodb-operator:PR-714-1d017663`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | failed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| pitr | passed |
| pitr-sharded | passed |
| smart-update | passed |
| version-service | failed |
| users | passed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/0149f10e1a54c14cc3371934728f608d89d2b45a
image: `perconalab/percona-server-mongodb-operator:PR-714-0149f10e`

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| service-per-pod | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | failed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/714/commits/0149f10e1a54c14cc3371934728f608d89d2b45a
image: `perconalab/percona-server-mongodb-operator:PR-714-0149f10e`

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
