### PR TITLE
K8SPSMDB-630 - PITR decrease waiting time up to 2 min

### PR DESCRIPTION
**Pull request by nmarukovich**
[K8SPSMDB-630](https://jira.percona.com/browse/K8SPSMDB-630) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by dalbani** [comment]
Out of curiosity, I wanted to have a look at the JIRA issue to understand (and maybe comment on) what the reason was behind this change.
But I don't have access to it. It's not the first time that I see that. It looks like JIRA issues opened by you guys at Percona are automatically forbidden to the general public.
Could you fix that?

**Comment by egegunes** [comment]
@dalbani Jira tasks we create are open to public by default. We just usually create maintenance tasks as internal. K8SPSMDB-630 is to leverage the new PBM configuration option for oplog uploads to shorten the PITR test duration.

**Comment by dalbani** [comment]
Oh, indeed, now that it look at the code change, I see that the change is only related to the test suite.
I thought it concerned the default value for general usage.

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| security-context | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| users | failed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/865/commits/8158203c87d2960c939c5bfe975e231a12b2b5b1
image: `perconalab/percona-server-mongodb-operator:PR-865-8158203c`

**Comment by tplavcic** [comment]
Please check the failed pitr-sharded test!

**Review by tplavcic — CHANGES_REQUESTED** [review]
Please check the failed pitr-sharded test!

**Comment by nmarukovich** [comment]
> Details



> Please check the failed pitr-sharded test!

sure!

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| self-healing-chaos | passed |
| scaling | passed |
| operator-self-healing | passed |
| security-context | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/865/commits/8158203c87d2960c939c5bfe975e231a12b2b5b1
image: `perconalab/percona-server-mongodb-operator:PR-865-8158203c`

**Review by egegunes — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
