### PR TITLE
K8SPSMDB-492 tests: Check pod restart after custom mongo config update

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPSMDB-492](https://jira.percona.com/browse/K8SPSMDB-492) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPSMDB-492

Modified tests to check if pod restarts after applying custom config

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| init-deploy | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| self-healing-chaos | passed |
| security-context | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | passed |
| data-sharded | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/445b9da759e14f5ebf933a18c53af6c6a47e2db8
image: `perconalab/percona-server-mongodb-operator:PR-725-445b9da7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | failed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| operator-self-healing-chaos | failed |
| upgrade | passed |
| users | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/b709ce689f4026e30bfaf74ff805bb8c514983dd
image: `perconalab/percona-server-mongodb-operator:PR-725-b709ce68`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | failed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| operator-self-healing | passed |
| service-per-pod | passed |
| operator-self-healing-chaos | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/43ac92e37a52c7c37b242d6cc25ae00760c9bc31
image: `perconalab/percona-server-mongodb-operator:PR-725-43ac92e3`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/43ac92e37a52c7c37b242d6cc25ae00760c9bc31
image: `perconalab/percona-server-mongodb-operator:PR-725-43ac92e3`

**Review by delgod — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| liveness | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/c93be52de3dea9b41d2999154aa827adb7305b4e
image: `perconalab/percona-server-mongodb-operator:PR-725-c93be52d`

**Review by tplavcic — CHANGES_REQUESTED** [review]
I believe this test will not test the change (but I could be wrong) - I'm commenting based on my tests from some time ago. If you don't have a secret with custom config and create a new one the pods will get restarted - so this test would pass anyway. We need to create a secret before starting the cluster and then update the content of that secret after the cluster is running.
Please check if this makes sense - maybe I'm missing something.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | failed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| upgrade | passed |
| liveness | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/1e6d5fb6c6a6b50e0e818af6b024fa4928272839
image: `perconalab/percona-server-mongodb-operator:PR-725-1e6d5fb6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| users | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/59027f4bd5c6c425e7d30199a64439cf21ab4ac8
image: `perconalab/percona-server-mongodb-operator:PR-725-59027f4b`

**Comment by pooknull** [comment]
> I believe this test will not test the change (but I could be wrong) - I'm commenting based on my tests from some time ago. If you don't have a secret with custom config and create a new one the pods will get restarted - so this test would pass anyway (even without the fix).
> We need to create a secret before starting the cluster and then update the content of that secret after the cluster is running and then check if the new value is used.
> Please check if this makes sense - maybe I'm missing something.

Yes, you are right. I fixed the tests in 59027f4bd5c6c425e7d30199a64439cf21ab4ac8, but they will pass only after merging #732

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| upgrade | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| pitr-sharded | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/6b92e085ec0b6ba8b8de83080c312dd0eed0d618
image: `perconalab/percona-server-mongodb-operator:PR-725-6b92e085`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| limits | passed |
| self-healing | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scheduled-backup | passed |
| security-context | passed |
| arbiter | passed |
| demand-backup-sharded | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| upgrade | passed |
| operator-self-healing | passed |
| upgrade-sharded | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| pitr | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |
| rs-shard-migration | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/f0f4f70de42dc1e886969eb1f6fa99175e98fd91
image: `perconalab/percona-server-mongodb-operator:PR-725-f0f4f70d`

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| storage | passed |
| data-sharded | passed |
| self-healing | passed |
| non-voting | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/f0f4f70de42dc1e886969eb1f6fa99175e98fd91
image: `perconalab/percona-server-mongodb-operator:PR-725-f0f4f70d`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| service-per-pod | passed |
| liveness | passed |
| operator-self-healing | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| pitr | failed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | failed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/725/commits/51e06cf09786b353a1ee6a70acdf2002cd309922
image: `perconalab/percona-server-mongodb-operator:PR-725-51e06cf0`

**Comment by ollevche** [comment]
Tests were OK today before the merge, here is [the report](https://cloud.cd.percona.com/job/cloud-psmdb-operator/job/PR-725/12/)

**Pull request merged**
