### PR TITLE
K8SPSMDB-173 tests: Storing custom configuration in configmaps and secrets for mongod

### PR DESCRIPTION
**Pull request by pooknull**
[K8SPSMDB-173](https://jira.percona.com/browse/K8SPSMDB-173) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPSMDB-173

Modified tests to check storing custom configuration in ConfigMaps and Secrets for mongod

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| upgrade | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/691/commits/0073f843e2865a603dd18ff1cbca6d9ef57da1cd
image: `perconalab/percona-server-mongodb-operator:PR-691-0073f843`

**Review by delgod — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | failed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| service-per-pod | passed |
| self-healing-chaos | passed |
| upgrade | passed |
| liveness | passed |
| upgrade-sharded | passed |
| smart-update | passed |
| operator-self-healing | passed |
| version-service | passed |
| pitr | passed |
| operator-self-healing-chaos | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/691/commits/bcee1f5884d8c7e4f9879c8a4368dffe498ecf2c
image: `perconalab/percona-server-mongodb-operator:PR-691-bcee1f58`

**Review by tplavcic — CHANGES_REQUESTED** [review]
Seems the `one-pod` test is failing with:
```
+ diff -u /mnt/jenkins/workspace/cloud-psmdb-operator_PR-691/e2e-tests/one-pod/compare/statefulset_one-pod-rs0-secret.yml /tmp/tmp.AFe2NepSyb/statefulset_one-pod-rs0.yml
--- /mnt/jenkins/workspace/cloud-psmdb-operator_PR-691/e2e-tests/one-pod/compare/statefulset_one-pod-rs0-secret.yml	2021-06-14 06:57:22.279825389 +0000
+++ /tmp/tmp.AFe2NepSyb/statefulset_one-pod-rs0.yml	2021-06-14 07:13:45.970194644 +0000
@@ -1,6 +1,7 @@
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
+  annotations: {}
   generation: 2
   labels:
     app.kubernetes.io/component: mongod
```
also please check the comments from github-actions.
Thanks!

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/691/commits/5aa16b6b58ff1a17d4dbcdda926d4f1f36753a60
image: `perconalab/percona-server-mongodb-operator:PR-691-5aa16b6b`

**Review by delgod — APPROVED** [review]

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
