### PR TITLE
1.11.0 docs

### PR DESCRIPTION
**Pull request by fiowro**

### CODE REVIEW

**Comment by tplavcic** [comment]
@dalbani It is being released today. Release is officially done once the git tag is set and release notes published, but we do push docker images few days before the release (although they can change during this time - I know it's confusing, but currently it is like that).

**Comment by dalbani** [comment]
@tplavcic: good to know, thanks for the feedback.
And congrats for this new release!

**Comment by dalbani** [comment]
Oh, one last annoying question: what about the `psmdb-operator` and `psmdb-db`Helm charts? 😀 
https://github.com/percona/percona-helm-charts/tree/main/charts/

**Comment by tplavcic** [comment]
@dalbani They will be updated this week! Usually we update them few days after the operator release, because of testing etc.
Your questions are not annoying - haha! Somehow they are expected and I'm not sure if we will change the process or document this somewhere.
Have a nice holidays!

**Review by tplavcic — APPROVED** [review]

**Pull request merged**
