### PR TITLE
CUSTOM-149: Fix liveness probe if custom replset name for 1.11.0

### PR DESCRIPTION
**Pull request by egegunes**
[CUSTOM-149](https://jira.percona.com/browse/CUSTOM-149) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

**CHANGE DESCRIPTION**
---
**Problem:**
*Short explanation of the problem.*

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?
- [ ] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [ ] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [ ] Is an E2E test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?
- [ ] Are OpenShift compare files changed for E2E tests (`compare/*-oc.yml`)?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Are the manifests (crd/bundle) regenerated if needed?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported MongoDB version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/2c8db2852b37c7bf1c5390038d418e80611a0331
image: `perconalab/percona-server-mongodb-operator:PR-1255-2c8db285`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| demand-backup | failed |
| limits | passed |
| scaling | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| security-context | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| monitoring-2-0 | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/2c8db2852b37c7bf1c5390038d418e80611a0331
image: `perconalab/percona-server-mongodb-operator:PR-1255-2c8db285`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| custom-replset-name | failed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| demand-backup | failed |
| limits | passed |
| scaling | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| security-context | passed |
| rs-shard-migration | passed |
| scheduled-backup | failed |
| one-pod | passed |
| monitoring-2-0 | failed |
| demand-backup-sharded | failed |
| arbiter | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/5974ccb821ab5ee504a36361f3dfb0f40fb14fa7
image: `perconalab/percona-server-mongodb-operator:PR-1255-5974ccb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| custom-replset-name | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| init-deploy | passed |
| limits | passed |
| scaling | failed |
| security-context | passed |
| rs-shard-migration | passed |
| scheduled-backup | failed |
| one-pod | passed |
| monitoring-2-0 | failed |
| arbiter | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/5974ccb821ab5ee504a36361f3dfb0f40fb14fa7
image: `perconalab/percona-server-mongodb-operator:PR-1255-5974ccb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| custom-replset-name | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| scheduled-backup | failed |
| one-pod | passed |
| demand-backup-sharded | failed |
| monitoring-2-0 | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | failed |
| upgrade | failed |
| version-service | passed |
| users | passed |
| data-sharded | failed |
| non-voting | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/8617f8f83d9ed894d28a3fefe44f706f4aee0842
image: `perconalab/percona-server-mongodb-operator:PR-1255-8617f8f8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| custom-replset-name | passed |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| self-healing | passed |
| limits | passed |
| monitoring-2-0 | failed |
| self-healing-chaos | passed |
| scaling | passed |
| operator-self-healing | passed |
| security-context | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| scheduled-backup | failed |
| version-service | passed |
| users | passed |
| data-sharded | failed |
| non-voting | passed |
| demand-backup-sharded | failed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/8617f8f83d9ed894d28a3fefe44f706f4aee0842
image: `perconalab/percona-server-mongodb-operator:PR-1255-8617f8f8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| custom-replset-name | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| one-pod | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| monitoring-2-0 | failed |
| rs-shard-migration | passed |
| scheduled-backup | passed |
| arbiter | passed |
| demand-backup-sharded | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| upgrade-sharded | failed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/9ed6138f2935d96f0cc94de42e68342cc8b4e89b
image: `perconalab/percona-server-mongodb-operator:PR-1255-9ed6138f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| custom-replset-name | passed |
| one-pod | passed |
| monitoring-2-0 | failed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | failed |
| upgrade-sharded | failed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/9ed6138f2935d96f0cc94de42e68342cc8b4e89b
image: `perconalab/percona-server-mongodb-operator:PR-1255-9ed6138f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | passed |
| custom-replset-name | failed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| demand-backup | failed |
| limits | passed |
| scaling | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| scheduled-backup | failed |
| security-context | failed |
| one-pod | failed |
| demand-backup-sharded | failed |
| rs-shard-migration | failed |
| monitoring-2-0 | failed |
| arbiter | failed |
| upgrade | failed |
| service-per-pod | failed |
| upgrade-sharded | failed |
| pitr | failed |
| liveness | failed |
| pitr-sharded | failed |
| smart-update | failed |
| version-service | failed |
| users | failed |
| data-sharded | failed |
| non-voting | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/ae1c45e1d3bdb3bc1f2b003f1aa63e650f977545
image: `perconalab/percona-server-mongodb-operator:PR-1255-ae1c45e1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| custom-replset-name | passed |
| one-pod | passed |
| monitoring-2-0 | failed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | failed |
| upgrade-sharded | failed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1255/commits/9ed6138f2935d96f0cc94de42e68342cc8b4e89b
image: `perconalab/percona-server-mongodb-operator:PR-1255-9ed6138f`

**Review by inelpandzic — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Pull request merged**
