### PR TITLE
CUSTOM-145: Custom replset name, hostAliases, liveness probe fix

### PR DESCRIPTION
**Pull request by egegunes**
[CUSTOM-145](https://jira.percona.com/browse/CUSTOM-145) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

**CHANGE DESCRIPTION**
---
**Problem:**
*Short explanation of the problem.*

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?
- [ ] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [ ] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [ ] Is an E2E test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?
- [ ] Are OpenShift compare files changed for E2E tests (`compare/*-oc.yml`)?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Are the manifests (crd/bundle) regenerated if needed?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported MongoDB version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| We run 0 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1248/commits/1d916611bd773d578877c41f3e90409e2a9ceec6
image: `perconalab/percona-server-mongodb-operator:PR-1248-v1.12.0-4-g1d916611`

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| We run 0 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1248/commits/1b9ff10d4e8c57562bee3930a4c7bcec1330037a
image: `perconalab/percona-server-mongodb-operator:PR-1248-v1.12.0-5-g1b9ff10d`

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| We run 0 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1248/commits/9bc10bc267408a659658c2a87deeef4db56270f9
image: `perconalab/percona-server-mongodb-operator:PR-1248-v1.12.0-6-g9bc10bc2`

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| cross-site-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/cross-site-sharded.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/init-deploy.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/storage.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/self-healing.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/self-healing-chaos.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/operator-self-healing.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/operator-self-healing-chaos.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/one-pod.log) |
| monitoring-2-0 | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/monitoring-2-0.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/upgrade-consistency.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/demand-backup.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/limits.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/scaling.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/security-context.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/rs-shard-migration.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/scheduled-backup.log) |
| arbiter | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/arbiter.log) |
| demand-backup-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/demand-backup-sharded.log) |
| service-per-pod | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/service-per-pod.log) |
| liveness | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1248/v1.12.0-7-g0a24e30f/liveness.log) |
| We run 20 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1248/commits/0a24e30f24627078ac512f987151c69abba3c8dd
image: `perconalab/percona-server-mongodb-operator:PR-1248-v1.12.0-7-g0a24e30f`

**Review by tplavcic — APPROVED** [review]

**Review by inelpandzic — APPROVED** [review]

**Pull request merged**
