### PR TITLE
K8SPSMDB-755: Fix tlsMode for mongos

### PR DESCRIPTION
**Pull request by egegunes**
[K8SPSMDB-755](https://jira.percona.com/browse/K8SPSMDB-755) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

**CHANGE DESCRIPTION**
---
**Problem:**
*Short explanation of the problem.*

**Cause:**
*Short explanation of the root cause of the issue if applicable.*

**Solution:**
*Short explanation of the solution we are providing with this PR.*

**CHECKLIST**
---
**Jira**
- [ ] Is the Jira ticket created and referenced properly?
- [ ] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [ ] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [ ] Is an E2E test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?
- [ ] Are OpenShift compare files changed for E2E tests (`compare/*-oc.yml`)?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported MongoDB version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

[K8SPSMDB-755]: https://perconadev.atlassian.net/browse/K8SPSMDB-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/arbiter.log) |
| balancer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/balancer.log) |
| custom-replset-name | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/custom-replset-name.log) |
| cross-site-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/cross-site-sharded.log) |
| data-at-rest-encryption | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/data-at-rest-encryption.log) |
| data-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/data-sharded.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/demand-backup.log) |
| demand-backup-eks-credentials | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/demand-backup-eks-credentials.log) |
| demand-backup-physical | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/demand-backup-physical.log) |
| demand-backup-physical-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/demand-backup-physical-sharded.log) |
| demand-backup-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/demand-backup-sharded.log) |
| expose-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/expose-sharded.log) |
| ignore-labels-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/ignore-labels-annotations.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/init-deploy.log) |
| finalizer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/finalizer.log) |
| ldap | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/ldap.log) |
| ldap-tls | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/ldap-tls.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/limits.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/liveness.log) |
| mongod-major-upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/mongod-major-upgrade.log) |
| mongod-major-upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/mongod-major-upgrade-sharded.log) |
| monitoring-2-0 | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/monitoring-2-0.log) |
| multi-cluster-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/multi-cluster-service.log) |
| non-voting | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/non-voting.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/one-pod.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/operator-self-healing-chaos.log) |
| pitr | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/pitr.log) |
| pitr-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/pitr-sharded.log) |
| pitr-physical | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/pitr-physical.log) |
| pvc-resize | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/pvc-resize.log) |
| recover-no-primary | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/recover-no-primary.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/rs-shard-migration.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/scaling.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/scheduled-backup.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/security-context.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/self-healing-chaos.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/service-per-pod.log) |
| serviceless-external-nodes | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/serviceless-external-nodes.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/smart-update.log) |
| split-horizon | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/split-horizon.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/storage.log) |
| tls-issue-cert-manager | [failure](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/tls-issue-cert-manager.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/upgrade.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/upgrade-consistency.log) |
| upgrade-consistency-sharded-tls | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/upgrade-consistency-sharded-tls.log) |
| upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/upgrade-sharded.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/users.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/4e5a0624/version-service.log) |
| We run 48 out of 48|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1540/commits/4e5a06242452da7948ab38099bda06596ef567f8
image: `perconalab/percona-server-mongodb-operator:PR-1540-4e5a0624`

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/arbiter.log) |
| balancer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/balancer.log) |
| custom-replset-name | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/custom-replset-name.log) |
| cross-site-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/cross-site-sharded.log) |
| data-at-rest-encryption | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/data-at-rest-encryption.log) |
| data-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/data-sharded.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/demand-backup.log) |
| demand-backup-eks-credentials | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/demand-backup-eks-credentials.log) |
| demand-backup-physical | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/demand-backup-physical.log) |
| demand-backup-physical-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/demand-backup-physical-sharded.log) |
| demand-backup-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/demand-backup-sharded.log) |
| expose-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/expose-sharded.log) |
| ignore-labels-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/ignore-labels-annotations.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/init-deploy.log) |
| finalizer | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/finalizer.log) |
| ldap | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/ldap.log) |
| ldap-tls | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/ldap-tls.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/limits.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/liveness.log) |
| mongod-major-upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/mongod-major-upgrade.log) |
| mongod-major-upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/mongod-major-upgrade-sharded.log) |
| monitoring-2-0 | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/monitoring-2-0.log) |
| multi-cluster-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/multi-cluster-service.log) |
| non-voting | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/non-voting.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/one-pod.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/operator-self-healing-chaos.log) |
| pitr | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/pitr.log) |
| pitr-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/pitr-sharded.log) |
| pitr-physical | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/pitr-physical.log) |
| pvc-resize | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/pvc-resize.log) |
| recover-no-primary | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/recover-no-primary.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/rs-shard-migration.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/scaling.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/scheduled-backup.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/security-context.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/self-healing-chaos.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/service-per-pod.log) |
| serviceless-external-nodes | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/serviceless-external-nodes.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/smart-update.log) |
| split-horizon | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/split-horizon.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/storage.log) |
| tls-issue-cert-manager | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/tls-issue-cert-manager.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/upgrade.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/upgrade-consistency.log) |
| upgrade-consistency-sharded-tls | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/upgrade-consistency-sharded-tls.log) |
| upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/upgrade-sharded.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/users.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1540/1d9c9379/version-service.log) |
| We run 48 out of 48|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1540/commits/1d9c93792f7264d46c30b78bcbb1b947d0951de9
image: `perconalab/percona-server-mongodb-operator:PR-1540-1d9c9379`

**Review by hors — APPROVED** [review]

**Comment by kantorcodes** [comment]
I believe this PR has broken running instances once the branch is pulled down - has this been tested?

**Comment by hors** [comment]
> I believe this PR has broken running instances once the branch is pulled down - has this been tested? 

It was tested by our e2e tests. After the merge our QA team will perform tests. Please do not use main branch for production needs. It can be unstable.

**Comment by hors** [comment]
@kantorcodes could you please provide your CR and we will test your case as well.

**Comment by kantorcodes** [comment]
> @kantorcodes could you please provide your CR and we will test your case as well.

On CR 1.16.0, cfg0-3 start, however mongos-0 reports: "Host failed in replica set" and "Error connecting to XX.XX.XX"

On CR 1.15.0, cfg-0 reports: "/opt/percona/ps-entry.sh: line 522: exec: numactl --interleave=all: not found" and `mongos-0` does not start at all.

**Comment by kantorcodes** [comment]
Do you have a recommended setup for running without TLS for the following variables?

`spec.image` in `cr.yaml` 
`upgradeOptions.apply` in `cr.yaml` 
`CR` in `cr.yaml` 
`spec.containers.image` in `bundle.yaml`

**Comment by hors** [comment]
> > @kantorcodes could you please provide your CR and we will test your case as well.

> On CR 1.15.0, cfg-0 reports: "/opt/percona/ps-entry.sh: line 522: exec: numactl --interleave=all: not found" and `mongos-0` does not start at all.

As you can see from release notes PSMDB 1.15 operator was tested with MongoDB 4.4.24, 5.0.20, and 6.0.9 and `numactl` was added to these docker files.
https://docs.percona.com/percona-operator-for-mongodb/RN/Kubernetes-Operator-for-PSMONGODB-RN1.15.0.html#supported-platforms:~:text=MongoDB%204.4.24%2C%205.0.20%2C%20and%206.0.9

**Comment by kantorcodes** [comment]
> https://docs.percona.com/percona-operator-for-mongodb/RN/Kubernetes-Operator-for-PSMONGODB-RN1.15.0.html#supported-platforms:~:text=MongoDB%204.4.24%2C%205.0.20%2C%20and%206.0.9

How would we force version 6.0.9 when specifying `spec.image` in `cr.yaml` ?

**Comment by hors** [comment]
> > https://docs.percona.com/percona-operator-for-mongodb/RN/Kubernetes-Operator-for-PSMONGODB-RN1.15.0.html#supported-platforms:~:text=MongoDB%204.4.24%2C%205.0.20%2C%20and%206.0.9
> 
> How would we force version 6.0.9 when specifying `spec.image` in `cr.yaml` ?

You can set it via https://github.com/percona/percona-server-mongodb-operator/blob/v1.15.0/deploy/cr.yaml#L15 option

**Comment by kantorcodes** [comment]
> > > https://docs.percona.com/percona-operator-for-mongodb/RN/Kubernetes-Operator-for-PSMONGODB-RN1.15.0.html#supported-platforms:~:text=MongoDB%204.4.24%2C%205.0.20%2C%20and%206.0.9
> > 
> > 
> > How would we force version 6.0.9 when specifying `spec.image` in `cr.yaml` ?
> 
> You can set it via https://github.com/percona/percona-server-mongodb-operator/blob/v1.15.0/deploy/cr.yaml#L15 option

What would be the correct value I mean?

**Comment by hors** [comment]
> > > > https://docs.percona.com/percona-operator-for-mongodb/RN/Kubernetes-Operator-for-PSMONGODB-RN1.15.0.html#supported-platforms:~:text=MongoDB%204.4.24%2C%205.0.20%2C%20and%206.0.9
> > > 
> > > 
> > > How would we force version 6.0.9 when specifying `spec.image` in `cr.yaml` ?
> > 
> > 
> > You can set it via https://github.com/percona/percona-server-mongodb-operator/blob/v1.15.0/deploy/cr.yaml#L15 option
> 
> What would be the correct value I mean?

Using this link, you can get the correct value as well :)

**Comment by hors** [comment]
> > @kantorcodes could you please provide your CR and we will test your case as well.
> 
> On CR 1.16.0, cfg0-3 start, however mongos-0 reports: "Host failed in replica set" and "Error connecting to XX.XX.XX"

Did you use the default CR? I can't reproduce it :(

**Comment by kantorcodes** [comment]
> > > > > https://docs.percona.com/percona-operator-for-mongodb/RN/Kubernetes-Operator-for-PSMONGODB-RN1.15.0.html#supported-platforms:~:text=MongoDB%204.4.24%2C%205.0.20%2C%20and%206.0.9
> > > > 
> > > > 
> > > > How would we force version 6.0.9 when specifying `spec.image` in `cr.yaml` ?
> > > 
> > > 
> > > You can set it via https://github.com/percona/percona-server-mongodb-operator/blob/v1.15.0/deploy/cr.yaml#L15 option
> > 
> > 
> > What would be the correct value I mean?
> 
> Using this link, you can get the correct value as well :)

Utilizing this combinations with TLS disabled, I am getting the follow error.  Happy to hop on a video call if you're willing to dissect this together further. Would that be helpful? 

```
spec:
#  platform: openshift
#  clusterServiceDNSSuffix: svc.cluster.local
  clusterServiceDNSMode: "External"
#  pause: true
#  unmanaged: false
  crVersion: 1.15.0
  image: percona/percona-server-mongodb:6.0.9-7
  imagePullPolicy: Always
  unsafeFlags:
    tls: true
  tls:
    allowInvalidCertificates: true
    mode: disabled
  #   enabled: false
#    # 90 days in hours
#    certValidityDuration: 2160h
#  imagePullSecrets:
#    - name: private-registry-credentials
#  initImage: perconalab/percona-server-mongodb-operator:main
#  initContainerSecurityContext: {}
  allowUnsafeConfigurations: true
  updateStrategy: SmartUpdate
  
```

{"t":{"$date":"2024-05-05T15:51:53.046Z"},"s":"F",  "c":"CONTROL",  "id":20574,   "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"need to enable TLS via the sslMode/tlsMode flag when using TLS configuration parameters"}}}

**Comment by kantorcodes** [comment]
Would specifying `initImage` be helpful with this new edge case?

**Comment by hors** [comment]
> Utilizing these combinations with TLS disabled, I am getting the following error.
> 
> `{"t":{"$date":"2024-05-05T15:51:53.046Z"},"s":"F", "c":"CONTROL", "id":20574, "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"need to enable TLS via the sslMode/tlsMode flag when using TLS configuration parameters"}}}`
> 
> Happy to hop on a video call if you're willing to dissect this together further. Would that be helpful? Note, `unsafeFlags` and `tls` were added after this PR went up. Simply specifying `allowUnsafeConfigurations` worked previously, I suspect a smart update cascaded issues here.
> 
> ```
> spec:
> #  platform: openshift
> #  clusterServiceDNSSuffix: svc.cluster.local
>   clusterServiceDNSMode: "External"
> #  pause: true
> #  unmanaged: false
>   crVersion: 1.15.0
>   image: percona/percona-server-mongodb:6.0.9-7
>   imagePullPolicy: Always
>   unsafeFlags:
>     tls: true
>   tls:
>     allowInvalidCertificates: true
>     mode: disabled
>   #   enabled: false
> #    # 90 days in hours
> #    certValidityDuration: 2160h
> #  imagePullSecrets:
> #    - name: private-registry-credentials
> #  initImage: perconalab/percona-server-mongodb-operator:main
> #  initContainerSecurityContext: {}
>   allowUnsafeConfigurations: true
>   updateStrategy: SmartUpdate
>   
> ```

Ok, thanks for CR. We will check it tomorrow in the morning.

**Comment by kantorcodes** [comment]
> > Utilizing these combinations with TLS disabled, I am getting the following error.
> > `{"t":{"$date":"2024-05-05T15:51:53.046Z"},"s":"F", "c":"CONTROL", "id":20574, "ctx":"-","msg":"Error during global initialization","attr":{"error":{"code":2,"codeName":"BadValue","errmsg":"need to enable TLS via the sslMode/tlsMode flag when using TLS configuration parameters"}}}`
> > Happy to hop on a video call if you're willing to dissect this together further. Would that be helpful? Note, `unsafeFlags` and `tls` were added after this PR went up. Simply specifying `allowUnsafeConfigurations` worked previously, I suspect a smart update cascaded issues here.
> > ```
> > spec:
> > #  platform: openshift
> > #  clusterServiceDNSSuffix: svc.cluster.local
> >   clusterServiceDNSMode: "External"
> > #  pause: true
> > #  unmanaged: false
> >   crVersion: 1.15.0
> >   image: percona/percona-server-mongodb:6.0.9-7
> >   imagePullPolicy: Always
> >   unsafeFlags:
> >     tls: true
> >   tls:
> >     allowInvalidCertificates: true
> >     mode: disabled
> >   #   enabled: false
> > #    # 90 days in hours
> > #    certValidityDuration: 2160h
> > #  imagePullSecrets:
> > #    - name: private-registry-credentials
> > #  initImage: perconalab/percona-server-mongodb-operator:main
> > #  initContainerSecurityContext: {}
> >   allowUnsafeConfigurations: true
> >   updateStrategy: SmartUpdate
> >   
> > ```
> 
> Ok, thanks for CR. We will check it tomorrow in the morning.

Would you have any ideas for a stopgap solution in production? I believe a smart update could affect other servers running with a similar setup and bring them down.

**Comment by hors** [comment]
> > > Happy to hop on a video call if you're willing to dissect this together further. Would that be helpful? Note, `unsafeFlags` and `tls` were added after this PR went up. Simply specifying `allowUnsafeConfigurations` worked previously, I suspect a smart update cascaded issues here.
> > > ```
> > > spec:
> > > #  platform: openshift
> > > #  clusterServiceDNSSuffix: svc.cluster.local
> > >   clusterServiceDNSMode: "External"
> > > #  pause: true
> > > #  unmanaged: false
> > >   crVersion: 1.15.0
> > >   image: percona/percona-server-mongodb:6.0.9-7
> > >   imagePullPolicy: Always
> > >   unsafeFlags:
> > >     tls: true
> > >   tls:
> > >     allowInvalidCertificates: true
> > >     mode: disabled
> > >   #   enabled: false
> > > #    # 90 days in hours
> > > #    certValidityDuration: 2160h
> > > #  imagePullSecrets:
> > > #    - name: private-registry-credentials
> > > #  initImage: perconalab/percona-server-mongodb-operator:main
> > > #  initContainerSecurityContext: {}
> > >   allowUnsafeConfigurations: true
> > >   updateStrategy: SmartUpdate
> > >   
> > > ```
> > 
> > 
> > Ok, thanks for CR. We will check it tomorrow in the morning.
> 
> Would you have any ideas for a stopgap solution in production? I believe a smart update could affect other servers running with a similar setup and bring them down.

Please do not use main branch for production. It was not tested by QA team. We run all needed tests before the release. You only need to use officially released versions of our operators.

**Comment by kantorcodes** [comment]
> > > > Happy to hop on a video call if you're willing to dissect this together further. Would that be helpful? Note, `unsafeFlags` and `tls` were added after this PR went up. Simply specifying `allowUnsafeConfigurations` worked previously, I suspect a smart update cascaded issues here.
> > > > ```
> > > > spec:
> > > > #  platform: openshift
> > > > #  clusterServiceDNSSuffix: svc.cluster.local
> > > >   clusterServiceDNSMode: "External"
> > > > #  pause: true
> > > > #  unmanaged: false
> > > >   crVersion: 1.15.0
> > > >   image: percona/percona-server-mongodb:6.0.9-7
> > > >   imagePullPolicy: Always
> > > >   unsafeFlags:
> > > >     tls: true
> > > >   tls:
> > > >     allowInvalidCertificates: true
> > > >     mode: disabled
> > > >   #   enabled: false
> > > > #    # 90 days in hours
> > > > #    certValidityDuration: 2160h
> > > > #  imagePullSecrets:
> > > > #    - name: private-registry-credentials
> > > > #  initImage: perconalab/percona-server-mongodb-operator:main
> > > > #  initContainerSecurityContext: {}
> > > >   allowUnsafeConfigurations: true
> > > >   updateStrategy: SmartUpdate
> > > >   
> > > > ```
> > > 
> > > 
> > > Ok, thanks for CR. We will check it tomorrow in the morning.
> > 
> > 
> > Would you have any ideas for a stopgap solution in production? I believe a smart update could affect other servers running with a similar setup and bring them down.
> 
> Please do not use main branch for production. It was not tested by QA team. We run all needed tests before the release. You only need to use officially released versions of our operators.

Understood --- however, despite switching off the `main` branch, the issue still persists, and looks like it can be replicated on a fresh setup as well.

**Comment by hors** [comment]
> > > > > Happy to hop on a video call if you're willing to dissect this together further. Would that be helpful? Note, `unsafeFlags` and `tls` were added after this PR went up. Simply specifying `allowUnsafeConfigurations` worked previously, I suspect a smart update cascaded issues here.
> 
> > > > > ```
> 
> > > > > spec:
> 
> > > > > #  platform: openshift
> 
> > > > > #  clusterServiceDNSSuffix: svc.cluster.local
> 
> > > > >   clusterServiceDNSMode: "External"
> 
> > > > > #  pause: true
> 
> > > > > #  unmanaged: false
> 
> > > > >   crVersion: 1.15.0
> 
> > > > >   image: percona/percona-server-mongodb:6.0.9-7
> 
> > > > >   imagePullPolicy: Always
> 
> > > > >   unsafeFlags:
> 
> > > > >     tls: true
> 
> > > > >   tls:
> 
> > > > >     allowInvalidCertificates: true
> 
> > > > >     mode: disabled
> 
> > > > >   #   enabled: false
> 
> > > > > #    # 90 days in hours
> 
> > > > > #    certValidityDuration: 2160h
> 
> > > > > #  imagePullSecrets:
> 
> > > > > #    - name: private-registry-credentials
> 
> > > > > #  initImage: perconalab/percona-server-mongodb-operator:main
> 
> > > > > #  initContainerSecurityContext: {}
> 
> > > > >   allowUnsafeConfigurations: true
> 
> > > > >   updateStrategy: SmartUpdate
> 
> > > > >   
> 
> > > > > ```
> 
> > > > 
> 
> > > > 
> 
> > > > Ok, thanks for CR. We will check it tomorrow in the morning.
> 
> > > 
> 
> > > 
> 
> > > Would you have any ideas for a stopgap solution in production? I believe a smart update could affect other servers running with a similar setup and bring them down.
> 
> > 
> 
> > Please do not use main branch for production. It was not tested by QA team. We run all needed tests before the release. You only need to use officially released versions of our operators.
> 
> 
> 
> Understood --- however, despite switching off the `main` branch, the issue still persists, and looks like it can be replicated on a fresh setup as well. 

It was merged into main branch only. It can't affect any versions which were related before. The v1.15.0 CRDa do not have new options and does not have a code which were added in main. Before the official release we will test this new options very carefully to be sure that new operator can work with old CR version.

**Pull request merged**
