### PR TITLE
K8SPSMDB-442 - fix stuck upgrade tests on 1.20

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPSMDB-442](https://jira.percona.com/browse/K8SPSMDB-442) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | failed |
| arbiter | failed |
| scheduled-backup | failed |
| operator-self-healing | failed |
| service-per-pod | failed |
| security-context | failed |
| demand-backup-sharded | failed |
| liveness | failed |
| upgrade | failed |
| rs-shard-migration | failed |
| smart-update | failed |
| upgrade-sharded | failed |
| version-service | failed |
| pitr | failed |
| users | failed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/655/commits/fa0667f1993a30042facaa430b225c98a8834ec1
image: `perconalab/percona-server-mongodb-operator:PR-655-fa0667f1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| storage | passed |
| self-healing | passed |
| operator-self-healing | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| security-context | passed |
| service-per-pod | passed |
| demand-backup-sharded | failed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/655/commits/fa0667f1993a30042facaa430b225c98a8834ec1
image: `perconalab/percona-server-mongodb-operator:PR-655-fa0667f1`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| operator-self-healing | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| upgrade-consistency | passed |
| service-per-pod | passed |
| demand-backup | passed |
| liveness | passed |
| scheduled-backup | passed |
| smart-update | passed |
| demand-backup-sharded | failed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/655/commits/fa0667f1993a30042facaa430b225c98a8834ec1
image: `perconalab/percona-server-mongodb-operator:PR-655-fa0667f1`

**Review by delgod — APPROVED** [review]
any reason behind the change?

**Comment by tplavcic** [comment]
@delgod for some reason deleting pvc's can get stuck in Terminating stage, like here: https://cloud.cd.percona.com/view/PSMDB/job/psmdb-operator-gke-version/387/execution/node/565/log/
```
NAME                        STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mongod-data-upgrade-rs0-0   Terminating   pvc-5825ee75-9be8-40bc-a277-20a622656dcf   3Gi        RWO            standard       7m34s
mongod-data-upgrade-rs0-1   Terminating   pvc-d9cfded4-a26c-45fa-b792-a6a75cabf750   3Gi        RWO            standard       7m9s
mongod-data-upgrade-rs0-2   Terminating   pvc-b4fd4c69-3d20-468a-be00-b92ed027a3fe   3Gi        RWO            standard       6m28s
```
it might be related to this: https://veducate.co.uk/kubernetes-pvc-terminating/

**Pull request merged**
