### PR TITLE
CLOUD-323 Kubectl error handling

### PR DESCRIPTION
**Pull request by cap1984**
In order to make tests more stable, kubectl repeat on fail
action has been added

### CODE REVIEW

**Comment by JNKPercona** [comment]
PSMDB operator docker  - perconalab/percona-server-mongodb-operator:PR-248-e6c9aa38

**Comment by delgod** [comment]
please update up to changes in PXC

**Comment by cap1984** [comment]
> please update up to changes in PXC

done

**Comment by JNKPercona** [comment]
PSMDB operator docker  - perconalab/percona-server-mongodb-operator:PR-248-0f0f0017

**Pull request merged**
