### PR TITLE
K8SPSMDB-266 Use planetext secrets

### PR DESCRIPTION
**Pull request by cap1984**
[K8SPSMDB-266](https://jira.percona.com/browse/K8SPSMDB-266)

Some users struggle to operate with manual base64 command,
so we are switching to plaintext mode

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-469-4a2697cd

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| init-deploy | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

**Review by hors — APPROVED** [review]
@cap1984 we need to do the same for PXCO. @delgod  right?

**Comment by cap1984** [comment]
> @cap1984 we need to do the same for PXCO. @delgod right?

https://github.com/percona/percona-xtradb-cluster-operator/pull/678
https://github.com/percona/percona-xtradb-cluster-operator/pull/679

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| security-context | passed |
| scheduled-backup | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |

**Pull request merged**
