### PR TITLE
default-cr test ignores custom IMAGE for operator

### PR DESCRIPTION
**Pull request by vorbidan**
[K8SPSMDB-832](https://jira.percona.com/browse/K8SPSMDB-832) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

https://jira.percona.com/browse/K8SPSMDB-832

Modified ./e2e-tests/default-cr/run to not reset the operator image to the default one

**CHANGE DESCRIPTION**
---
**Problem:**
default-cr e2e test ignores custom operator IMAGE

**Cause:**
Lines 51 - 59 in e2e-tests/default-cr/run effectively override the all CRDs and an operator CR with defaults, and ignore all related customizations introduced in functions, particularly in the create_infra function.

**Solution:**
Removing lines 51 - 59 in e2e-tests/default-cr/run makes the custom  Operator IMAGE to be used in the test.

**CHECKLIST**
---
**Jira**
- [x] Is the Jira ticket created and referenced properly?
- [ ] Does the Jira ticket have the proper statuses for documentation (`Needs Doc`) and QA (`Needs QA`)?
- [ ] Does the Jira ticket link to the proper milestone (Fix Version field)?

**Tests**
- [x] Are E2E tests passing?
- [ ] Are unit tests passing?
- [ ] Are linting tests passing?
- [ ] Is an E2E test/test case added for the new feature/change?
- [ ] Are unit tests added where appropriate?
- [ ] Are OpenShift compare files changed for E2E tests (`compare/*-oc.yml`)?

**Config/Logging/Testability**
- [ ] Are all needed new/changed options added to default YAML files?
- [ ] Are the manifests (crd/bundle) regenerated if needed?
- [ ] Did we add proper logging messages for operator actions?
- [ ] Did we ensure compatibility with the previous version or cluster upgrade process?
- [ ] Does the change support oldest and newest supported MongoDB version?
- [ ] Does the change support oldest and newest supported Kubernetes version?

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/init-deploy.log) |
| cross-site-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/cross-site-sharded.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/one-pod.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/upgrade-consistency.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/storage.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/demand-backup.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/self-healing-chaos.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/limits.log) |
| ignore-labels-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/ignore-labels-annotations.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/scaling.log) |
| monitoring-2-0 | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/monitoring-2-0.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/scheduled-backup.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/security-context.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/operator-self-healing-chaos.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/rs-shard-migration.log) |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/arbiter.log) |
| demand-backup-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/demand-backup-sharded.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/service-per-pod.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/upgrade.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/liveness.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/smart-update.log) |
| upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/upgrade-sharded.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/version-service.log) |
| pitr | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/pitr.log) |
| pitr-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/pitr-sharded.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/users.log) |
| data-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/data-sharded.log) |
| non-voting | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/non-voting.log) |
| demand-backup-eks-credentials | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/demand-backup-eks-credentials.log) |
| data-at-rest-encryption | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/3b4f3e89/data-at-rest-encryption.log) |
| We run 30 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1117/commits/3b4f3e89571700bdb36e826883d55d58c693b889
image: `perconalab/percona-server-mongodb-operator:PR-1117-3b4f3e89`

**Comment by tplavcic** [comment]
Hi @vorbidan !
Our `default-cr` test is designed to run specifically with all the default yaml files without changes and we run it only on the release branch (as you can see you cannot see it in the tests report here in the github).
Do you have some specific reason you want to run it on custom images?

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/one-pod.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/init-deploy.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/storage.log) |
| cross-site-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/cross-site-sharded.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/upgrade-consistency.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/demand-backup.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/self-healing-chaos.log) |
| ignore-labels-annotations | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/ignore-labels-annotations.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/limits.log) |
| monitoring-2-0 | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/monitoring-2-0.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/scaling.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/scheduled-backup.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/operator-self-healing-chaos.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/security-context.log) |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/arbiter.log) |
| demand-backup-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/demand-backup-sharded.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/rs-shard-migration.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/service-per-pod.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/liveness.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/smart-update.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/upgrade.log) |
| upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/upgrade-sharded.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/version-service.log) |
| pitr | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/pitr.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/users.log) |
| pitr-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/pitr-sharded.log) |
| data-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/data-sharded.log) |
| non-voting | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/non-voting.log) |
| demand-backup-eks-credentials | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/demand-backup-eks-credentials.log) |
| data-at-rest-encryption | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1117/4ab466a0/data-at-rest-encryption.log) |
| We run 30 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1117/commits/4ab466a05ec760e2601476244da55c85823c32aa
image: `perconalab/percona-server-mongodb-operator:PR-1117-4ab466a0`

**Review by nmarukovich — CHANGES_REQUESTED** [review]
As @tplavcic mentioned we use it only in release cycle. @vorbidan do you have any specific reason to run it?

**Comment by vorbidan** [comment]
I was following the [README.md](https://github.com/percona/percona-server-mongodb-operator/blob/main/e2e-tests/README.md) for testing the operator. It does not mention the fact that `default-cr` is the special case and should not be run as part of tests for Operator PR. Quite the opposite, it points to the link where one can set environment variables to affect the tests runtime and test the custom built operator by setting the IMAGE environment variable.
When one executes `./e2e-tests/run` as mentioned in the README _with_ the IMAGE environment variable, this particular test overrides the operator image reference and fails, since the default image `perconalab/percona-server-mongodb-operator:main` cannot be pulled. 
Now - this was true about 1 month ago. This test could not pull the image at `perconalab/percona-server-mongodb-operator:main`. Could have been a temporary glitch, because I can now pull this image.

Still, seems confusing, that this test does not really test the operator _with_ introduced changes, but rather tests the operator version, which is pushed to registry by Percona.

We can close this PR as irrelevant, if that is the true intent.

**Comment by nmarukovich** [comment]
> I was following the [README.md](https://github.com/percona/percona-server-mongodb-operator/blob/main/e2e-tests/README.md) for testing the operator. It does not mention the fact that `default-cr` is the special case and should not be run as part of tests for Operator PR. Quite the opposite, it points to the link where one can set environment variables to affect the tests runtime and test the custom built operator by setting the IMAGE environment variable. When one executes `./e2e-tests/run` as mentioned in the README _with_ the IMAGE environment variable, this particular test overrides the operator image reference and fails, since the default image `perconalab/percona-server-mongodb-operator:main` cannot be pulled. Now - this was true about 1 month ago. This test could not pull the image at `perconalab/percona-server-mongodb-operator:main`. Could have been a temporary glitch, because I can now pull this image.
> 
> Still, seems confusing, that this test does not really test the operator _with_ introduced changes, but rather tests the operator version, which is pushed to registry by Percona.
> 
> We can close this PR as irrelevant, if that is the true intent.

@vorbidan I see you point. What can we do to make your experience better? You are correct we don't assume that people use default-cr to check something. We use it for release process with hardcoded images to be sure that any variables do not change cr-default images. 
If we update README with some notes about it would be it enough? 
What problem did you try to resolve originally? Do need any help with it?

**Pull request closed without merging**
