### PR TITLE
Migrate to cert-manager.io/v1 from cert-manager.io/v1alpha2

### PR DESCRIPTION
**Pull request by kvaster**
cert-manager is already >v1.0 for a long time (v1.6.1 now) and cert-manager.io/v1alpha2 is deprecated already and removed for kubernets <= 1.14:

https://cert-manager.io/docs/installation/upgrading/upgrading-0.16-1.0/#kubernetes-1-14-and-below

Bumping cert-manager crd to new versions also requires to bump operator-sdk and other modules versions.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| arbiter | passed |
| scaling | passed |
| security-context | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| rs-shard-migration | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| users | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| demand-backup-sharded | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/863/commits/1e38a0b43fe779aa4c69a5376de9528394bf350d
image: `perconalab/percona-server-mongodb-operator:PR-863-1e38a0b4`

**Comment by egegunes** [comment]
Hello @kvaster, thank you for your contribution. I started to work on the same issue recently in https://github.com/percona/percona-server-mongodb-operator/pull/860. It's also WIP but progressed a bit further than this PR.

**Comment by kvaster** [comment]
Thanks. My changes are basically:
* Bump deps
* Add ctx from k8s api
* Migrate to v1 api for cert-manager
* Some minor changes according to operator-sdk bump

Generally this PR works for us, but I can't run tests unfortunatelly and have no access to CI logs :(

**Comment by kvaster** [comment]
Will use my own version until PR #860 will be finished :)

b.t.w, vendored modules make PRs looks very messy :(

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | failed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | passed |
| pitr-sharded | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/863/commits/4d3912ef51a3c7794cb90c4d3e16bdfa87fed478
image: `perconalab/percona-server-mongodb-operator:PR-863-4d3912ef`

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/storage.log) |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/one-pod.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/init-deploy.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/upgrade-consistency.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/limits.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/demand-backup.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/self-healing.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/self-healing-chaos.log) |
| monitoring-2-0 | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/monitoring-2-0.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/scaling.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/security-context.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/operator-self-healing.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/scheduled-backup.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/operator-self-healing-chaos.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/rs-shard-migration.log) |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/arbiter.log) |
| demand-backup-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/demand-backup-sharded.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/service-per-pod.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/liveness.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/smart-update.log) |
| upgrade | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/upgrade.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/version-service.log) |
| upgrade-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/upgrade-sharded.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/users.log) |
| pitr | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/pitr.log) |
| data-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/data-sharded.log) |
| non-voting | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/non-voting.log) |
| pitr-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/eb9ed170/pitr-sharded.log) |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/863/commits/eb9ed170429fefd341368305b157f2cb96564b4a
image: `perconalab/percona-server-mongodb-operator:PR-863-eb9ed170`

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| one-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/one-pod.log) |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/init-deploy.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/limits.log) |
| monitoring-2-0 | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/monitoring-2-0.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/scaling.log) |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/arbiter.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/security-context.log) |
| rs-shard-migration | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/rs-shard-migration.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/service-per-pod.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/liveness.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/smart-update.log) |
| version-service | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/version-service.log) |
| users | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/users.log) |
| data-sharded | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/data-sharded.log) |
| non-voting | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-863/acef6353/non-voting.log) |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/863/commits/acef6353b13a67687e174afa8a2c10699aadc74f
image: `perconalab/percona-server-mongodb-operator:PR-863-acef6353`

**Comment by kvaster** [comment]
Seems only non-voting should be fixed from my side! Is this really my changes ?

**Comment by kvaster** [comment]
Also I can't see failure logs :(

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>cloud-psmdb-operator/PR-863/acef6353/non-voting.log</Key>
<RequestId>S3DQZR3DYM132BN4</RequestId>
<HostId>jKcYccliICrlfdzzNGYJjH8lINiK+Yd9nxrLGdBM7O/j5ddzhqVIDMS4vAEZd6VDtm8TuqTMemM=</HostId>
</Error>
```

**Comment by jimethn** [comment]
@kvaster I built your branch, but ran the tests from `main`, and they all passed. Maybe your branch just needs rebased?

**Comment by kvaster** [comment]
> @kvaster I built your branch, but ran the tests from `main`, and they all passed. Maybe your branch just needs rebased?

It is already rebased.

**Comment by egegunes** [comment]
@kvaster We're going to merge #860 and close this PR soon. If you have any feedback please ping me.

**Comment by kvaster** [comment]
Thanks!

**Comment by egegunes** [comment]
@kvaster #860 is merged. You can use the `v1` API of cert-manager now. I'm closing this PR.

**Pull request closed without merging**
