### PR TITLE
K8SPSMDB-635: Add labels to backup pod template

### PR DESCRIPTION
**Pull request by ipronko**
[K8SPSMDB-635](https://jira.percona.com/browse/K8SPSMDB-635) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

Add custom labels for backup parameter of PerconaServerMongoDB resource

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| scaling | passed |
| security-context | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| arbiter | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| upgrade | failed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/869/commits/a435602bb816042e0c5dc871226049f52b21cbb0
image: `perconalab/percona-server-mongodb-operator:PR-869-a435602b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| monitoring-2-0 | failed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| security-context | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| arbiter | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/869/commits/dea1f91421e37bf221fe60275c22a8b295f7e03b
image: `perconalab/percona-server-mongodb-operator:PR-869-dea1f914`

**Review by egegunes — APPROVED** [review]

**Comment by egegunes** [comment]
Hi @ipronko, thank you for your contribution. Changes are LGTM. Please the following changes to fix the tests:

* Fix the labels in `e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml`

The diff:
```diff
+ diff -u /mnt/jenkins/workspace/cloud-psmdb-operator_PR-869/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml /tmp/tmp.F63hUXMFIA/cronjob.batch_sec-context-backup-each-hour.yml
--- /mnt/jenkins/workspace/cloud-psmdb-operator_PR-869/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml	2022-01-28 08:55:20.786821326 +0000
+++ /tmp/tmp.F63hUXMFIA/cronjob.batch_sec-context-backup-each-hour.yml	2022-01-28 09:45:04.828490853 +0000
@@ -28,7 +28,14 @@
         app.kubernetes.io/replset: general
     spec:
       template:
-        metadata: {}
+        metadata:
+          labels:
+            app.kubernetes.io/component: backup-schedule
+            app.kubernetes.io/instance: sec-context
+            app.kubernetes.io/managed-by: percona-server-mongodb-operator
+            app.kubernetes.io/name: percona-server-mongodb
+            app.kubernetes.io/part-of: percona-server-mongodb
+            app.kubernetes.io/replset: general
         spec:
           containers:
             - args:
```

* Fix the labels in `e2e-tests/scheduled-backup/compare/cronjob_*.yml`

The diff:

```diff
+ diff -u /mnt/jenkins/workspace/cloud-psmdb-operator_PR-869/e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio.yml /tmp/tmp.8BKaD5zsk6/cronjob_some-name-backup-every-min-minio.yml
--- /mnt/jenkins/workspace/cloud-psmdb-operator_PR-869/e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio.yml	2022-01-28 08:55:20.786821326 +0000
+++ /tmp/tmp.8BKaD5zsk6/cronjob_some-name-backup-every-min-minio.yml	2022-01-28 09:35:12.782400755 +0000
@@ -28,7 +28,14 @@
         app.kubernetes.io/replset: general
     spec:
       template:
-        metadata: {}
+        metadata:
+          labels:
+            app.kubernetes.io/component: backup-schedule
+            app.kubernetes.io/instance: some-name
+            app.kubernetes.io/managed-by: percona-server-mongodb-operator
+            app.kubernetes.io/name: percona-server-mongodb
+            app.kubernetes.io/part-of: percona-server-mongodb
+            app.kubernetes.io/replset: general
         spec:
           containers:
             - args:
```

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| demand-backup-sharded | failed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | passed |
| data-sharded | passed |
| upgrade-sharded | passed |
| non-voting | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/869/commits/adb46ba6b4f7d0951079cce3902da0eb7322d2ed
image: `perconalab/percona-server-mongodb-operator:PR-869-adb46ba6`

**Review by egegunes — APPROVED** [review]
LGTM. `monitoring-2-0` failure is not related to these changes.

**Review by delgod — APPROVED** [review]

**Pull request merged**
