### PR TITLE
K8SPSMDB-192 added cursorTimeoutMillis parameter

### PR DESCRIPTION
**Pull request by xprt64**

### CODE REVIEW

**Comment by it-percona** [comment]
[CLA assistant check](https://cla-assistant.percona.com:443/percona/percona-server-mongodb-operator?pullRequest=351) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/percona-server-mongodb-operator?pullRequest=351) before we can accept your contribution.<br/><hr/>**Constantin Galbenu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/percona-server-mongodb-operator?pullRequest=351) it.</sub>

**Comment by delgod** [comment]
@xprt64 please sign CLA https://cla-assistant.percona.com/percona/percona-server-mongodb-operator?pullRequest=351

**Comment by xprt64** [comment]
I have signed it, I get the message "You have signed the CLA for percona/percona-server-mongodb-operator"

**Comment by xprt64** [comment]
@delgod  I have signed it, I get the message "You have signed the CLA for percona/percona-server-mongodb-operator"

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | failed |
| scheduled-backup | passed |
| service-per-pod | failed |
| liveness | passed |

**Comment by delgod** [comment]
Hi @xprt64 
I don't know what is going, but I still don't see you in the list of persons who signed CLA for this repository.
you can create an issue if needed https://github.com/cla-assistant/cla-assistant/issues

**Comment by xprt64** [comment]
I've pushed using a different/wrong email address. Please ignore this PR, I've made another.

**Pull request closed without merging**
