### PR TITLE
K8SPSMDB-525 - switch images to main tag for main branch

### PR DESCRIPTION
**Pull request by spron-in**
[K8SPSMDB-525](https://jira.percona.com/browse/K8SPSMDB-525) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

I would like to trigger the discussion about switching the tags to main.
```
 spec:
      containers:
        - name: percona-server-mongodb-operator
          image: percona/percona-server-mongodb-operator:1.9.0
```  
   vs
```
 spec:
      containers:
        - name: percona-server-mongodb-operator
          image: perconalab/percona-server-mongodb-operator:main 
```

Lets discuss.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| upgrade-sharded | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/734/commits/7965018d05fccbc49fe5b811a3bf904976a8489d
image: `perconalab/percona-server-mongodb-operator:PR-734-7965018d`

**Review by tplavcic — CHANGES_REQUESTED** [review]
To use the new features you would have to change `apiVersion: psmdb.percona.com/v1-9-0` and `crVersion: 1.9.0` also to the next version.

**Review by delgod — APPROVED** [review]

**Comment by spron-in** [comment]
> To use the new features you would have to change `apiVersion: psmdb.percona.com/v1-9-0` and `crVersion: 1.9.0` also to the next version.

Any specific CR version for main branch? 
Or it is always the next version?

**Comment by tplavcic** [comment]
> > To use the new features you would have to change `apiVersion: psmdb.percona.com/v1-9-0` and `crVersion: 1.9.0` also to the next version.
> 
> Any specific CR version for main branch?
> Or it is always the next version?
> @tplavcic

From what I know it's always the next version.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/734/commits/5685d9a5d69783d25ed5f46348d99cdf3fda16a4
image: `perconalab/percona-server-mongodb-operator:PR-734-5685d9a5`

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| scheduled-backup | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| upgrade | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/734/commits/809d1db3d8e5ed1ef7f133c2c2f51ad2b9759db2
image: `perconalab/percona-server-mongodb-operator:PR-734-809d1db3`

**Pull request merged**
