### PR TITLE
[K8SPSMDB-568] allow to upgrade from 4.4 to 5.0

### PR DESCRIPTION
**Pull request by defbin**
[K8SPSMDB-568](https://jira.percona.com/browse/K8SPSMDB-568) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by egegunes — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | failed |
| scheduled-backup | failed |
| arbiter | passed |
| demand-backup-sharded | failed |
| scaling | passed |
| upgrade | passed |
| security-context | failed |
| service-per-pod | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| pitr | failed |
| pitr-sharded | failed |
| smart-update | passed |
| version-service | passed |
| users | failed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/815/commits/ac1bc8406697e3545e32cf4161d1fd8aae0c0324
image: `perconalab/percona-server-mongodb-operator:PR-815-ac1bc840`

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | failed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| one-pod | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |
| scheduled-backup | failed |
| data-sharded | passed |
| non-voting | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | failed |
| rs-shard-migration | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/815/commits/ac1bc8406697e3545e32cf4161d1fd8aae0c0324
image: `perconalab/percona-server-mongodb-operator:PR-815-ac1bc840`

**Review by hors — CHANGES_REQUESTED** [review]
we need to fix installation of Minio

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| one-pod | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/815/commits/ac1bc8406697e3545e32cf4161d1fd8aae0c0324
image: `perconalab/percona-server-mongodb-operator:PR-815-ac1bc840`

**Review by hors — APPROVED** [review]

**Pull request merged**
