### PR TITLE
K8SPSMDB-324: Add disruption budget for mongos

### PR DESCRIPTION
**Pull request by blez**
[K8SPSMDB-324](https://jira.percona.com/browse/K8SPSMDB-324)

### CODE REVIEW

**Comment by tplavcic** [comment]
I believe we should set defaults (and not just commented) in cr.yaml for this and also for antiAffinity (for which we put, but commented), because in that case whoever looks at cr.yaml will be immediately aware what is default and active.

**Review by delgod — DISMISSED** [review]

**Review by hors — APPROVED** [review]

**Comment by blez** [comment]
@tplavcic https://github.com/percona/percona-server-mongodb-operator/pull/473/commits/88351fe14e1f4c8fa79eaa78a6c8eb542efc9f2c

**Review by tplavcic — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-473-57c3c3c9

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| arbiter | passed |
| security-context | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| scheduled-backup | passed |
| version-service | passed |
| users | passed |
| demand-backup-sharded | passed |

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-473-88351fe1

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| upgrade | passed |
| storage | passed |
| monitoring | passed |
| self-healing | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| operator-self-healing | passed |
| scheduled-backup | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

**Pull request merged**
