### PR TITLE
K8SPSMDB-384: Increase initial delay for monogs' readiness probe

### PR DESCRIPTION
**Pull request by blez**
[K8SPSMDB-384](https://jira.percona.com/browse/K8SPSMDB-384) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | failed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| scheduled-backup | passed |
| version-service | passed |
| demand-backup-sharded | failed |
| users | passed |
| upgrade | passed |
| upgrade-sharded | failed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/634/commits/d49392f4365a1d4fa2ca2f8ca805c21691f85898
image: `perconalab/percona-server-mongodb-operator:PR-634-d49392f4`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| limits | passed |
| scheduled-backup | passed |
| scaling | passed |
| arbiter | passed |
| demand-backup-sharded | failed |
| security-context | passed |
| operator-self-healing | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| upgrade | passed |
| upgrade-sharded | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/634/commits/5a276e2e0ea1aacf92eb43963e4441b650c3ccd1
image: `perconalab/percona-server-mongodb-operator:PR-634-5a276e2e`

**Review by qJkee — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | failed |
| storage | passed |
| self-healing | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | passed |
| upgrade-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/634/commits/5a276e2e0ea1aacf92eb43963e4441b650c3ccd1
image: `perconalab/percona-server-mongodb-operator:PR-634-5a276e2e`

**Review by hors — CHANGES_REQUESTED** [review]
@blez I do not think that it is good idea to increase this value. Why is it needed at all? As I can see readiness probe works. Yes, we have some failures in the log. How does it affect the users?

**Comment by blez** [comment]
@hors 
When cluster starting, k8s starts to do readiness probe on `mongos` but it fails because of uninitialized replicasets.
This RP fixes the issue with a low priority https://jira.percona.com/browse/K8SPSMDB-384

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| arbiter | passed |
| rs-shard-migration | passed |
| service-per-pod | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/634/commits/859325884c7adf9c891c97dce52601e6eb654bc4
image: `perconalab/percona-server-mongodb-operator:PR-634-85932588`

**Pull request closed without merging**
