### PR TITLE
K8SPSMDB-323 - Change default PSMDB to 4.4 for running the tests

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPSMDB-323](https://jira.percona.com/browse/K8SPSMDB-323)

Storage test is failing and it seems related to either image or PSMDB version:
https://jira.percona.com/browse/K8SPSMDB-356

### CODE REVIEW

**Review by hors — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| one-pod | failed |
| init-deploy | failed |
| upgrade | failed |
| upgrade-consistency | failed |
| monitoring | passed |
| limits | passed |
| demand-backup | failed |
| self-healing | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scheduled-backup | failed |
| security-context | failed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | failed |
| storage | passed |
| upgrade | failed |
| one-pod | passed |
| upgrade-consistency | passed |
| demand-backup | failed |
| monitoring | passed |
| self-healing | passed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| security-context | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| scheduled-backup | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | failed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring | passed |
| limits | passed |
| monitoring-2-0 | failed |
| scaling | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| service-per-pod | failed |

**Review by hors — CHANGES_REQUESTED** [review]
Please add the  task number to the commit message and we need to have all tests passed.

**Review by hors — CHANGES_REQUESTED** [review]
@tplavcic  As  I understood we are going to support PSMDB 4.4 in 1.6.0 , so we need to fix these tests as soon as possible.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| upgrade | failed |
| upgrade-consistency | passed |
| storage | passed |
| monitoring | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing | passed |
| demand-backup-sharded | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

**Comment by tplavcic** [comment]
@hors don't worry, all is good ;) Only upgrade test is failing for 4.4 because there is no 4.4 version to upgrade from for older operator version.
Actually found some issue with smart-update and different image names, created PR here: https://github.com/percona/percona-server-mongodb-operator/pull/483

**Review by hors — DISMISSED** [review]

**Review by delgod — DISMISSED** [review]

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| demand-backup-sharded | passed |
| version-service | passed |
| upgrade | failed |
| upgrade-sharded | failed |
| users | passed |

**Review by hors — DISMISSED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | failed |
| upgrade-consistency | passed |
| demand-backup | failed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| self-healing | passed |
| smart-update | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| version-service | passed |
| users | passed |
| demand-backup-sharded | failed |
| upgrade | failed |
| upgrade-sharded | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| init-deploy | passed |
| upgrade-consistency | passed |
| one-pod | passed |
| demand-backup | failed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| rs-shard-migration | passed |
| self-healing | passed |
| service-per-pod | passed |
| scheduled-backup | failed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| demand-backup-sharded | failed |
| upgrade | passed |
| upgrade-sharded | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| self-healing | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| storage | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| self-healing | passed |
| operator-self-healing | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| upgrade-consistency | passed |
| init-deploy | passed |
| demand-backup | passed |
| limits | passed |
| scheduled-backup | passed |
| scaling | passed |
| demand-backup-sharded | passed |
| security-context | passed |
| one-pod | passed |
| upgrade | passed |
| rs-shard-migration | passed |
| monitoring-2-0 | passed |
| upgrade-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| self-healing | passed |
| operator-self-healing | passed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| storage | failed |
| version-service | passed |
| users | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| self-healing | passed |
| operator-self-healing | passed |

**Comment by delgod** [comment]
I am closing PR because it is needed to rename the default branch to `main`.

@tplavcic please reopen this PR to the `main` branch.

**Pull request closed without merging**
