### PR TITLE
[K8SPSMDB-602]: setFCV flag causes a thread leak

### PR DESCRIPTION
**Pull request by defbin**
[K8SPSMDB-602](https://jira.percona.com/browse/K8SPSMDB-602) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by delgod — DISMISSED** [review]

**Review by hors — DISMISSED** [review]
@defbin  As I can see the issue was fixed but we need to wait for the  tests results.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| pitr-sharded | failed |
| users | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/830/commits/12a7ceba0911b4deb02b7e84c6112566052a5cd1
image: `perconalab/percona-server-mongodb-operator:PR-830-12a7ceba`

**Comment by defbin** [comment]
pls don't merge it for now. found issue in the code

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/830/commits/e1aabc936c2b3ec00cb40633a250777aa792058c
image: `perconalab/percona-server-mongodb-operator:PR-830-e1aabc93`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/830/commits/8db879f73d5c0eba56e4f29afa739dbe8d1e61f1
image: `perconalab/percona-server-mongodb-operator:PR-830-8db879f7`

**Review by delgod — APPROVED** [review]

**Review by hors — APPROVED** [review]

**Pull request merged**
