### PR TITLE
K8SPSMDB-550: Fix arbiter service if rs exposed

### PR DESCRIPTION
**Pull request by egegunes**

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | failed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| liveness | passed |
| pitr | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/756/commits/0f65468b70634bef871802d0fadce1502fe7038b
image: `perconalab/percona-server-mongodb-operator:PR-756-0f65468b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/756/commits/0f65468b70634bef871802d0fadce1502fe7038b
image: `perconalab/percona-server-mongodb-operator:PR-756-0f65468b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/756/commits/7db4c39a094a1b0d7c522065be2447ed65aa9e26
image: `perconalab/percona-server-mongodb-operator:PR-756-7db4c39a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| monitoring-2-0 | passed |
| limits | passed |
| self-healing | passed |
| arbiter | passed |
| scaling | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| security-context | passed |
| operator-self-healing | passed |
| liveness | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/756/commits/7db4c39a094a1b0d7c522065be2447ed65aa9e26
image: `perconalab/percona-server-mongodb-operator:PR-756-7db4c39a`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | failed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| upgrade | passed |
| liveness | passed |
| upgrade-sharded | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| pitr | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/756/commits/cbb4e03202c5246fbeaf8ffb1cda6f95a8c27044
image: `perconalab/percona-server-mongodb-operator:PR-756-cbb4e032`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/756/commits/cbb4e03202c5246fbeaf8ffb1cda6f95a8c27044
image: `perconalab/percona-server-mongodb-operator:PR-756-cbb4e032`

**Review by defbin — APPROVED** [review]

**Review by nonemax — APPROVED** [review]

**Pull request merged**
