### PR TITLE
K8SPSMDB-256 - Increment versions after 1.5.0 release

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPSMDB-256](https://jira.percona.com/browse/K8SPSMDB-256)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | failed |
| one-pod | failed |
| upgrade | passed |
| init-deploy | failed |
| self-healing | failed |
| limits | failed |
| operator-self-healing | failed |
| monitoring | failed |
| scaling | failed |
| security-context | failed |
| monitoring-2-0 | failed |
| upgrade-consistency | failed |
| arbiter | failed |
| service-per-pod | failed |
| demand-backup | failed |
| liveness | failed |
| users | failed |
| scheduled-backup | failed |

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | failed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| security-context | passed |
| arbiter | passed |
| self-healing | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| operator-self-healing | passed |
| liveness | passed |
| users | passed |

**Comment by JNKPercona** [comment]
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-427-3bc075b8

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| users | passed |

**Review by cap1984 — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Pull request merged**
