### PR TITLE
K8SPSMDB-574: Set certificate duration for external certificates to 100 years

### PR DESCRIPTION
**Pull request by yaron**
[K8SPSMDB-574](https://jira.percona.com/browse/K8SPSMDB-574) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

For the local ca certificate the enddate is set to the year 9999, the cert-manager managed version gets a default duration of only 90 days. This change makes the cert-manager managed ca certificate valid for 1000 years. We need this stability to allow other services to learn the ca-certificate. If we have automatic rotation every 60 days (2/3th of 90 days) we will have to update the ca cert on every service that talks to mongodb.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/b6fad1fda3875cb9fd20de1c1b40d4cb518d6ba8
image: `perconalab/percona-server-mongodb-operator:PR-779-b6fad1fd`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/b6fad1fda3875cb9fd20de1c1b40d4cb518d6ba8
image: `perconalab/percona-server-mongodb-operator:PR-779-b6fad1fd`

**Comment by egegunes** [comment]
Hi @yaron, thank you for your contribution.

The build is failing:

```
pkg/controller/perconaservermongodb/ssl.go:84:4: cannot use "8760000h" (type string) as type *"k8s.io/apimachinery/pkg/apis/meta/v1".Duration in field value
```

**Comment by yaron** [comment]
I've made it a valid time.Duration value, but had to change it to 100 years because 1000 years will overflow time.Duration (constant 31536000000000000000 overflows time.Duration).

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/6cf9ec6be9621f8323acfb69ef799a6a27b5034d
image: `perconalab/percona-server-mongodb-operator:PR-779-6cf9ec6b`

**Comment by egegunes** [comment]
@yaron the build is still failing:

```
pkg/controller/perconaservermongodb/ssl.go:84:4: cannot use 876000 * time.Hour (type time.Duration) as type *"k8s.io/apimachinery/pkg/apis/meta/v1".Duration in field value
```

You need to do like this:

```
metav1.Duration{Duration: 876000 * time.Hour}
```

**Comment by yaron** [comment]
Sorry about that, I was not using an IDE for the previous commits because I thought they where simple enough. This time I did and ran the e2e-tests/build script to verify that it actually builds.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | failed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/51eb5eb7e154b54477742b87b5d3bab473596fbc
image: `perconalab/percona-server-mongodb-operator:PR-779-51eb5eb7`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| limits | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| scaling | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| security-context | passed |
| operator-self-healing | passed |
| liveness | passed |
| rs-shard-migration | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | failed |
| non-voting | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/51eb5eb7e154b54477742b87b5d3bab473596fbc
image: `perconalab/percona-server-mongodb-operator:PR-779-51eb5eb7`

**Comment by egegunes** [comment]
@yaron tests look OK. `demand-backup-sharded` is failed due to an unrelated issue.

**Comment by egegunes** [comment]
@delgod could you take a look?

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/a0212c2f4e5715138cf8884664659132d3261806
image: `perconalab/percona-server-mongodb-operator:PR-779-a0212c2f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | passed |
| non-voting | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/a0212c2f4e5715138cf8884664659132d3261806
image: `perconalab/percona-server-mongodb-operator:PR-779-a0212c2f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| storage | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| operator-self-healing-chaos | passed |
| version-service | passed |
| users | passed |
| upgrade | passed |
| data-sharded | passed |
| upgrade-sharded | passed |
| non-voting | passed |
| pitr | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/2ae68e4f02bd7faa11b8bc9495adb6e4eb8fc4eb
image: `perconalab/percona-server-mongodb-operator:PR-779-2ae68e4f`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/c3d79a73cb8c4eed1275ea915f0c537917ca4b5e
image: `perconalab/percona-server-mongodb-operator:PR-779-c3d79a73`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | failed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| scheduled-backup | passed |
| version-service | passed |
| users | failed |
| demand-backup-sharded | failed |
| data-sharded | passed |
| upgrade | failed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/779/commits/7f9133459f2c653da02f4bb03e71a7313809fbb2
image: `perconalab/percona-server-mongodb-operator:PR-779-7f913345`

**Pull request merged**
