### PR TITLE
K8SPSMDB-121 - Add antiAffinityTopologyKey for mongos and fix indentation for auditLog

### PR DESCRIPTION
**Pull request by tplavcic**
[K8SPSMDB-121](https://jira.percona.com/browse/K8SPSMDB-121)

### CODE REVIEW

**Review by delgod — APPROVED** [review]

**Comment by tplavcic** [comment]
@delgod @blez 
But it seems that we should add this whole chunk instead because we have it for other node types and resources/limits seem to be missing also:
```
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
#       advanced:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: kubernetes.io/e2e-az-name
#                 operator: In
#                 values:
#                 - e2e-az1
#                 - e2e-az2
#     tolerations:
#     - key: "node.alpha.kubernetes.io/unreachable"
#       operator: "Exists"
#       effect: "NoExecute"
#       tolerationSeconds: 6000
#     priorityClassName: high-priority
#     annotations:
#       iam.amazonaws.com/role: role-arn
#     labels:
#       rack: rack-22
#     nodeSelector:
#       disktype: ssd
#    schedulerName: "default"
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
```

**Comment by delgod** [comment]
@tplavcic yes please

**Comment by JNKPercona** [comment]
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-454-34b311dc

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| scaling | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

**Comment by JNKPercona** [comment]
PSMDB operator docker - perconalab/percona-server-mongodb-operator:PR-454-40d5c4a2

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade | passed |
| self-healing | passed |
| monitoring | passed |
| limits | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| demand-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| arbiter | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |

**Review by delgod — APPROVED** [review]

**Pull request merged**
