### PR TITLE
K8SPSMDB-415: Fix smart update for arbiter

### PR DESCRIPTION
**Pull request by blez**
[K8SPSMDB-415](https://jira.percona.com/browse/K8SPSMDB-415) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Review by delgod — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/51f80154ef27e4d63de42ef6128e87460d3770d8
image: `perconalab/percona-server-mongodb-operator:PR-594-51f80154`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| one-pod | passed |
| self-healing | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| security-context | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| storage | passed |
| self-healing | passed |
| operator-self-healing | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| self-healing | passed |
| limits | passed |
| operator-self-healing | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| storage | passed |
| self-healing | passed |
| data-sharded | passed |
| operator-self-healing | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| upgrade-consistency | passed |
| rs-shard-migration | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/594/commits/8dfbfeb85b19c330ea35de1121b28660b63286fd
image: `perconalab/percona-server-mongodb-operator:PR-594-8dfbfeb8`

**Pull request merged**
