### PR TITLE
[K8SPSMDB-601] Compression set in PerconaServerMongoDB's task is missing in PerconaServerMongoDBBackup

### PR DESCRIPTION
**Pull request by dalbani**
[K8SPSMDB-601](https://jira.percona.com/browse/K8SPSMDB-601) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

Resolves https://jira.percona.com/browse/K8SPSMDB-601 and https://jira.percona.com/browse/K8SPSMDB-622.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| upgrade-consistency | passed |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| demand-backup | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| limits | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| scheduled-backup | failed |
| arbiter | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |
| security-context | failed |
| service-per-pod | passed |
| liveness | passed |
| rs-shard-migration | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| demand-backup-sharded | failed |
| upgrade | failed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/34b989506f6a30576826d6118305e8a8088a4151
image: `perconalab/percona-server-mongodb-operator:PR-817-34b98950`

**Comment by dalbani** [comment]
Could I get access to Jenkins in order to find out why some tests didn't pass?

**Comment by egegunes** [comment]
Hey @dalbani, thank you for your contribution. Changes LGTM. 

`security-context` and `scheduled-backup` tests are failing because of the new added field. You need to change the curl command in comparison files for these tests: [cronjob.batch_sec-context-backup-each-hour.yml in security-context](https://github.com/percona/percona-server-mongodb-operator/blob/main/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml) and [cronjob-* in scheduled-backup](https://github.com/percona/percona-server-mongodb-operator/tree/main/e2e-tests/scheduled-backup/compare).

New command should be:
```
"curl \\\n\t\t\t-vvv \\\n\t\t\t-X POST \\\n\t\t\t--cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt \\\n\t\t\t-H \"Content-Type: application/json\" \\\n\t\t\t-H \"Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)\" \\\n\t\t\t--data \"{\\\"kind\\\":\\\"PerconaServerMongoDBBackup\\\",\\\"apiVersion\\\":\\\"psmdb.percona.com/v1\\\",\\\"metadata\\\":{\\\"generateName\\\":\\\"cron-${psmdbCluster:0:16}-$(date -u '+%Y%m%d%H%M%S')-\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"ancestor\\\":\\\"sec-context-backup-each-hour\\\",\\\"cluster\\\":\\\"${psmdbCluster}\\\",\\\"type\\\":\\\"cron\\\"},\\\"finalizers\\\":[\\\"delete-backup\\\"]},\\\"spec\\\":{\\\"psmdbCluster\\\":\\\"${psmdbCluster}\\\",\\\"storageName\\\":\\\"minio\\\",\\\"compressionType\\\":\\\"gzip\\\"},\\\"status\\\":{}}\" \\\n\t\t\thttps://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/apis/psmdb.percona.com/v1/namespaces/${NAMESPACE}/perconaservermongodbbackups"
```

`demand-backup-sharded` test is failing with cluster crash. Are you able to run tests in your environment?

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| security-context | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| arbiter | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/e86e32d8e8004616d012d3f50bb27bcaa468608d
image: `perconalab/percona-server-mongodb-operator:PR-817-e86e32d8`

**Comment by dalbani** [comment]
Thanks @egegunes, I will have a look.

**Comment by dalbani** [comment]
@egegunes, I couldn't get the E2E tests to run locally in a Kubernetes environment based on Docker for Desktop.
I saw in the README that it should work with Minikube, so I suppose it should be compatible with Docker for Desktop as well?
The issue I'm running into is due to ant-affinity rules for `my-cluster-name-rs0-1`:
```
0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity
      rules, 1 node(s) didn't match pod anti-affinity rules.
```
The first pod, `rs0-0`, was successfully scheduled. But given that there's a single node, Kubernetes refuses scheduling additional pods.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | failed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | failed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | failed |
| data-sharded | passed |
| non-voting | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/eaf8eee25f555254980537c3dc971902ec7f810d
image: `perconalab/percona-server-mongodb-operator:PR-817-eaf8eee2`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| rs-shard-migration | passed |
| smart-update | passed |
| upgrade | failed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/182e114e96899f514c47c27584c13a9bf9d795b6
image: `perconalab/percona-server-mongodb-operator:PR-817-182e114e`

**Comment by egegunes** [comment]
Yes, tests may not be suitable to run on a single node. `demand-backup-sharded` test passed multiple times, I guess it was a false negative. Just checked the test outputs and comparison still failing due to curl command. Command should be exactly:

```
"curl \\\n\t\t\t-vvv \\\n\t\t\t-X POST \\\n\t\t\t--cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt \\\n\t\t\t-H \"Content-Type: application/json\" \\\n\t\t\t-H \"Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)\" \\\n\t\t\t--data \"{\\\"kind\\\":\\\"PerconaServerMongoDBBackup\\\",\\\"apiVersion\\\":\\\"psmdb.percona.com/v1\\\",\\\"metadata\\\":{\\\"generateName\\\":\\\"cron-${clusterName:0:16}-$(date -u '+%Y%m%d%H%M%S')-\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"ancestor\\\":\\\"sec-context-backup-each-hour\\\",\\\"cluster\\\":\\\"${clusterName}\\\",\\\"type\\\":\\\"cron\\\"},\\\"finalizers\\\":[\\\"delete-backup\\\"]},\\\"spec\\\":{\\\"clusterName\\\":\\\"${clusterName}\\\",\\\"storageName\\\":\\\"minio\\\",\\\"compressionType\\\":\\\"gzip\\\"},\\\"status\\\":{}}\" \\\n\t\t\thttps://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/apis/psmdb.percona.com/v1/namespaces/${NAMESPACE}/perconaservermongodbbackups"
```

It'll fix `scheduled-backup` and `security-context` tests. I'll look into why `upgrade` test is failing.

**Comment by dalbani** [comment]
I tried to fix the `curl` command based on what I _thought_ would be the expected value. But apparently it's still not correct.
Speaking of the E2E tests, what are the minimum requirements in terms of the Kubernetes cluster?
How many nodes are required? How much resources should they have (memory in particular) in order to be able to properly run all the tests?

**Comment by dalbani** [comment]
And I also get this error by the way:
```
...
+ diff -u /Users/dalbani/IdeaProjects/github.com/dalbani/percona-server-mongodb-operator.git/e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg.yml /var/folders/nq/gfz9v85x30jdwqytpq7vwwx40000gp/T/tmp.MZeldLT6/statefulset_my-cluster-name-cfg.yml
--- /Users/dalbani/IdeaProjects/github.com/dalbani/percona-server-mongodb-operator.git/e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg.yml	2021-11-30 21:19:14.000000000 +0100
+++ /var/folders/nq/gfz9v85x30jdwqytpq7vwwx40000gp/T/tmp.MZeldLT6/statefulset_my-cluster-name-cfg.yml	2021-12-07 11:28:32.000000000 +0100
@@ -119,7 +119,7 @@
               name: mongodb
               protocol: TCP
           readinessProbe:
-            failureThreshold: 8
+            failureThreshold: 3
             initialDelaySeconds: 10
             periodSeconds: 3
             successThreshold: 1
+ fail default-cr
+ local test=default-cr
+ echo 'test default-cr failed'
test default-cr failed
+ exit 1
```
Where could it come from?!?

**Review by delgod — DISMISSED** [review]

**Comment by dalbani** [comment]
Rebased on `main`.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/db48f796f98ec426d1cd831f4a4b288ba9e4092f
image: `perconalab/percona-server-mongodb-operator:PR-817-db48f796`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | failed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| liveness | passed |
| rs-shard-migration | failed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | failed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-sharded | failed |
| pitr | failed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/e7e0c4378be2f68a3359d4efc3ee8a87b7f490f1
image: `perconalab/percona-server-mongodb-operator:PR-817-e7e0c437`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| init-deploy | passed |
| data-sharded | passed |
| limits | passed |
| non-voting | passed |
| scaling | passed |
| security-context | failed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | failed |
| demand-backup-sharded | passed |
| upgrade | failed |
| rs-shard-migration | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/e7e0c4378be2f68a3359d4efc3ee8a87b7f490f1
image: `perconalab/percona-server-mongodb-operator:PR-817-e7e0c437`

**Comment by dalbani** [comment]
Is there a way to get detailed logs of the E2E tests performed by Jenkins?
I've tried running the tests against a larger and more beefier Kubernetes cluster, but it keeps failing.
Could you share the Kubernetes setup that you use for the E2E tests?

**Comment by egegunes** [comment]
@dalbani Tests run on GKE 1.20 with 3 nodes (n1-standard-4). 

Please change the curl command as I said earlier:
 
> Just checked the test outputs and comparison still failing due to curl command. Command should be exactly:
> 
> ```
> "curl \\\n\t\t\t-vvv \\\n\t\t\t-X POST \\\n\t\t\t--cacert /run/secrets/kubernetes.io/serviceaccount/ca.crt \\\n\t\t\t-H \"Content-Type: application/json\" \\\n\t\t\t-H \"Authorization: Bearer $(cat /run/secrets/kubernetes.io/serviceaccount/token)\" \\\n\t\t\t--data \"{\\\"kind\\\":\\\"PerconaServerMongoDBBackup\\\",\\\"apiVersion\\\":\\\"psmdb.percona.com/v1\\\",\\\"metadata\\\":{\\\"generateName\\\":\\\"cron-${clusterName:0:16}-$(date -u '+%Y%m%d%H%M%S')-\\\",\\\"creationTimestamp\\\":null,\\\"labels\\\":{\\\"ancestor\\\":\\\"sec-context-backup-each-hour\\\",\\\"cluster\\\":\\\"${clusterName}\\\",\\\"type\\\":\\\"cron\\\"},\\\"finalizers\\\":[\\\"delete-backup\\\"]},\\\"spec\\\":{\\\"clusterName\\\":\\\"${clusterName}\\\",\\\"storageName\\\":\\\"minio\\\",\\\"compressionType\\\":\\\"gzip\\\"},\\\"status\\\":{}}\" \\\n\t\t\thttps://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/apis/psmdb.percona.com/v1/namespaces/${NAMESPACE}/perconaservermongodbbackups"
> ```

I'll investigate the `upgrade` test failure once the others pass.

**Comment by dalbani** [comment]
> Tests run on GKE 1.20 with 3 nodes (n1-standard-4).

Strange, I've just tested against a similar, brand new GKE cluster and I still get the same issue I mentioned earlier:
```
NAMESPACE         NAME                                                  READY   STATUS    RESTARTS   AGE
default-cr-7802   my-cluster-name-cfg-0                                 2/2     Running   0          9m44s
default-cr-7802   my-cluster-name-cfg-1                                 2/2     Running   0          9m16s
default-cr-7802   my-cluster-name-cfg-2                                 2/2     Running   0          10m
default-cr-7802   my-cluster-name-mongos-59b667555d-8rxbh               1/1     Running   0          6m59s
default-cr-7802   my-cluster-name-mongos-59b667555d-krg2h               1/1     Running   0          6m37s
default-cr-7802   my-cluster-name-mongos-59b667555d-n2ph2               1/1     Running   0          7m19s
default-cr-7802   my-cluster-name-rs0-0                                 2/2     Running   0          8m14s
default-cr-7802   my-cluster-name-rs0-1                                 2/2     Running   0          7m44s
default-cr-7802   my-cluster-name-rs0-2                                 2/2     Running   0          8m46s
default-cr-7802   my-cluster-name-rs0-3                                 0/2     Pending   0          6m
default-cr-7802   my-cluster-name-rs0-arbiter-0                         1/1     Running   0          6m
default-cr-7802   percona-server-mongodb-operator-5dd88ff7f7-z4r2q      1/1     Running   0          21m
default-cr-7802   psmdb-client-7b9f978649-gc8qf                         1/1     Running   0          20m
kube-system       event-exporter-gke-5479fd58c8-9767z                   2/2     Running   0          23m
kube-system       fluentbit-gke-gzdjt                                   2/2     Running   0          22m
...
```
Here you can see that `my-cluster-name-rs0-3` is pending, due to anti-affinity rules, as per the pod status.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| monitoring-2-0 | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | failed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| demand-backup-sharded | failed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| upgrade | failed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/a40e59e3fdb25d31becc5c480b531f959f796125
image: `perconalab/percona-server-mongodb-operator:PR-817-a40e59e3`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| rs-shard-migration | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| users | passed |
| upgrade-sharded | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/3a8aeec37fe91d1409cb1f62b4cb5e6178136f57
image: `perconalab/percona-server-mongodb-operator:PR-817-3a8aeec3`

**Comment by dalbani** [comment]
After quite a lot of fiddling, I think I got the E2E tests to work again.
So I think the code can be merged if you agree.

**Review by egegunes — APPROVED** [review]

**Comment by dalbani** [comment]
Rebased on `main`.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/c89907a71ff11fddd060fec2414d06ca8c7d1a97
image: `perconalab/percona-server-mongodb-operator:PR-817-c89907a7`

**Comment by dalbani** [comment]
Rebased on `main`.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| data-sharded | passed |
| pitr | passed |
| non-voting | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/f8f8a54b283c4eebace2583390fd1da9a58d47c0
image: `perconalab/percona-server-mongodb-operator:PR-817-f8f8a54b`

**Comment by dalbani** [comment]
Oh dear, `pitr-sharded` is now failing 😓 
That reminds me of my question above: could we somehow be able to see the Jenkins logs in order to precisely figure out why particular tests fail?
Otherwise it's frustrating, I have the feeling of flying blind... Thanks!

**Comment by egegunes** [comment]
Most probably `pitr-sharded` is failed due to timeout. I triggered rebuild.

I agree with you, let me talk with the team to provide read only access to Jenkins logs.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/f8f8a54b283c4eebace2583390fd1da9a58d47c0
image: `perconalab/percona-server-mongodb-operator:PR-817-f8f8a54b`

**Review by egegunes — APPROVED** [review]

**Comment by dalbani** [comment]
Rebased on `main`.

Once https://github.com/percona/percona-backup-mongodb/pull/619 is merged, I will update this PR to include support for the compression *level* as well.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| storage | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| demand-backup | passed |
| scaling | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| monitoring-2-0 | failed |
| upgrade | passed |
| upgrade-sharded | passed |
| arbiter | passed |
| pitr | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| pitr-sharded | failed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/a63b003bc742a660aff7e6c26c35a3b12dd03263
image: `perconalab/percona-server-mongodb-operator:PR-817-a63b003b`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| one-pod | passed |
| monitoring-2-0 | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/a63b003bc742a660aff7e6c26c35a3b12dd03263
image: `perconalab/percona-server-mongodb-operator:PR-817-a63b003b`

**Comment by dalbani** [comment]
Rebased on `main`.
And I've added the `CompressionLevel` property to match what's now available in PBM.

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | passed |
| data-sharded | passed |
| non-voting | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/97e9cb857cf1f5a9d2cf7f714b0ef7ef0ec4b808
image: `perconalab/percona-server-mongodb-operator:PR-817-97e9cb85`

**Review by defbin — DISMISSED** [review]
lgtm

**Comment by defbin** [comment]
@dalbani could you please add compressionLevel field to `deploy/cr.yaml` to have example

**Comment by dalbani** [comment]
> @dalbani could you please add compressionLevel field to `deploy/cr.yaml` to have example

Done.

**Review by defbin — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| self-healing-chaos | passed |
| limits | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| scaling | passed |
| arbiter | passed |
| security-context | passed |
| operator-self-healing | passed |
| operator-self-healing-chaos | passed |
| scheduled-backup | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| users | passed |
| pitr | failed |
| data-sharded | passed |
| non-voting | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/fd792f92b3c4317c4c633477297d6e5951b68d7c
image: `perconalab/percona-server-mongodb-operator:PR-817-fd792f92`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| storage | passed |
| one-pod | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| self-healing-chaos | passed |
| arbiter | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| operator-self-healing-chaos | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |
| non-voting | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/817/commits/fd792f92b3c4317c4c633477297d6e5951b68d7c
image: `perconalab/percona-server-mongodb-operator:PR-817-fd792f92`

**Review by egegunes — APPROVED** [review]

**Review by delgod — APPROVED** [review]

**Pull request merged**
