### PR TITLE
K8SPSMDB-451: Check cluster endpoint for ready status

### PR DESCRIPTION
**Pull request by egegunes**
[K8SPSMDB-451](https://jira.percona.com/browse/K8SPSMDB-451) [Powered by Pull Request Badge](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Review by qJkee — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| init-deploy | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| self-healing | passed |
| version-service | passed |
| operator-self-healing | passed |
| demand-backup-sharded | failed |
| upgrade | failed |
| users | passed |
| upgrade-sharded | failed |
| pitr | passed |
| data-sharded | passed |
| pitr-sharded | failed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/685/commits/d286ee13c4fcc7553dbf487be1331b057199612b
image: `perconalab/percona-server-mongodb-operator:PR-685-d286ee13`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| security-context | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/685/commits/4c3b74b94d4127c4ca626a00fc7668ef0ad07230
image: `perconalab/percona-server-mongodb-operator:PR-685-4c3b74b9`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| limits | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| demand-backup | passed |
| scheduled-backup | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| upgrade-sharded | passed |
| pitr | passed |
| pitr-sharded | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| arbiter | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| liveness | passed |
| operator-self-healing | passed |
| smart-update | passed |
| version-service | passed |
| operator-self-healing-chaos | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/685/commits/4c3b74b94d4127c4ca626a00fc7668ef0ad07230
image: `perconalab/percona-server-mongodb-operator:PR-685-4c3b74b9`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| service-per-pod | passed |
| self-healing-chaos | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| upgrade | passed |
| operator-self-healing | passed |
| upgrade-sharded | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| smart-update | passed |
| pitr | passed |
| version-service | passed |
| users | failed |
| pitr-sharded | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/685/commits/5f8dc447bff7b2799d060fe96509632f9dac07ff
image: `perconalab/percona-server-mongodb-operator:PR-685-5f8dc447`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| service-per-pod | passed |
| rs-shard-migration | passed |
| demand-backup-sharded | passed |
| self-healing-chaos | passed |
| liveness | passed |
| upgrade | passed |
| smart-update | passed |
| upgrade-sharded | passed |
| operator-self-healing | passed |
| version-service | passed |
| pitr | passed |
| operator-self-healing-chaos | passed |
| users | passed |
| data-sharded | passed |
| pitr-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/685/commits/a6e265f6503a20f747ae3d2f98345d17f5633d8e
image: `perconalab/percona-server-mongodb-operator:PR-685-a6e265f6`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| self-healing-chaos | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| operator-self-healing | passed |
| upgrade | passed |
| liveness | passed |
| operator-self-healing-chaos | passed |
| upgrade-sharded | passed |
| smart-update | passed |
| version-service | passed |
| pitr | passed |
| users | passed |
| pitr-sharded | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/685/commits/275a89f94644d339fe1ce134cf2ed12742f7adfb
image: `perconalab/percona-server-mongodb-operator:PR-685-275a89f9`

**Pull request merged**
