### PR TITLE
fix: infinite loop in cluster reconcile

### PR DESCRIPTION
**Pull request by pastequo**
Hello,

I'm mostly creating this PR to start a discussion.

We are currently observing a lot of requests coming from the operator to the mongodb cluster (roughly 150 op/ minut / mongod) during the whole cluster lifespan. Every ~5s, connections are opened and close in the provisioned mongodb cluster.

After some investigation, it seems to me that the reconcile loop never stops, even when the cluster has reached the targeted state. At this point, I think the reconcile loop should only be triggered by events. But since it loops, the operator queries mongo to get some info, hence the high number of requests & open/close connection.

---

I think a change of behavior had been introduced over time:

https://github.com/percona/percona-server-mongodb-operator/commit/461cf447a#diff-fd80dba0eb6b57cfdcc7680051e7541d1aa1d9ffbfc9559ba1fd1171f863bf12
Line 48:  `reconcileIn:   time.Second * 5,`
Line 91-93:
```golang
	rr := reconcile.Result{
		RequeueAfter: r.reconcileIn,
	}
```
Line 140: `return reconcile.Result{}, nil`

At this stage, the reconcile loop was not re-queuing the task (see line 140), but it added a default retry in `rr`

https://github.com/percona/percona-server-mongodb-operator/commit/61eb6e381#diff-fd80dba0eb6b57cfdcc7680051e7541d1aa1d9ffbfc9559ba1fd1171f863bf12

Line 147: `return rr, nil`

Now the code loops "forever". I'm not sure if this was the intention, or if the target was to make it loop once

---

The previous commits I mentioned are almost 4 years old and I think some code had been merged thanks to this behavior. For example, the Reconcile loop doesn't wait for the pod to be ready, it just keep going and defer that mission to the next iterations. The problem is that, from my tests, it doesn't stop

So there will be probably some side effects trying to revert this now

---

Another way of limiting the impact of this effect could be to reuse mongodb connection: if there are meant to be used every 5s, it might worth keeping it open. I haven't tried to implement this solution, which doesn't seem to be the right thing to do from where I stand ;) 

---

I've made minimum testing (replicaset + sharding in my local environment). I haven't run the repo tests yet.

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| init-deploy | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/init-deploy.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/storage.log) |
| cross-site-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/cross-site-sharded.log) |
| one-pod | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/one-pod.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/upgrade-consistency.log) |
| demand-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/demand-backup.log) |
| self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/self-healing.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/self-healing-chaos.log) |
| limits | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/limits.log) |
| monitoring-2-0 | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/monitoring-2-0.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/scaling.log) |
| security-context | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/security-context.log) |
| operator-self-healing | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/operator-self-healing.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/operator-self-healing-chaos.log) |
| scheduled-backup | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/scheduled-backup.log) |
| demand-backup-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/demand-backup-sharded.log) |
| rs-shard-migration | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/rs-shard-migration.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/upgrade.log) |
| arbiter | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/arbiter.log) |
| service-per-pod | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/service-per-pod.log) |
| liveness | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/liveness.log) |
| smart-update | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/smart-update.log) |
| version-service | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/version-service.log) |
| upgrade-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/upgrade-sharded.log) |
| pitr | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/pitr.log) |
| pitr-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/pitr-sharded.log) |
| users | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/users.log) |
| data-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/data-sharded.log) |
| non-voting | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/non-voting.log) |
| demand-backup-eks-credentials | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/demand-backup-eks-credentials.log) |
| data-at-rest-encryption | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/1217911a/data-at-rest-encryption.log) |
| We run 31 out of 30|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1068/commits/1217911ac8f11e54c0c809e1a3852380f59a82b3
image: `perconalab/percona-server-mongodb-operator:PR-1068-1217911a`

**Comment by gabeguz** [comment]
Any feedback on this MR?

**Comment by pastequo** [comment]
I'm still interested in any feedback 😉

**Comment by egegunes** [comment]
@pastequo sorry for sleeping on this. I'll try to take a look and start the discussion in this week.

**Comment by egegunes** [comment]
Hi @pastequo,

Thank you for your contribution. We were talking about this problem internally for some time but couldn't prioritize it in previous releases. Your changes look good to me and I feel like landing this may be easier than I thought initially.

Having said that, these changes are not complete. `psmdb_controller` needs to watch the resources it created and receive reconcile events if something is changed. From top of my mind, we need to watch at least:

1. Statefulsets
2. ConfigMaps
3. Secrets
4. Services

Example of watching:

```
err = c.Watch(&source.Kind{Type: &appsv1.StatefulSet{}}, &handler.EnqueueRequestForOwner{OwnerType: &api.PerconaServerMongoDB{}, IsController: true})
if err != nil {
	return err
}
```

Even if we watch everything, the operator won't notice if someone changes the replica set configuration with mongo client and won't be able to fix it. We have some options to trigger reconcile by monitoring external sources but I'm not sure if we need to do this in the scope of this PR. We need a decision on this shortcoming for merging this PR tough. @hors @spron-in  

Once we watch all required objects, we'll see how tests will behave.

**Comment by pastequo** [comment]
Yes this PR is very likely to be incomplete. I added the code changes to have some support for the discussion, not to get it merge. I didn't know you already tracked this issue 👍

**Comment by JNKPercona** [comment]
| Test name | Status |
| ------------- | ------------- |
| one-pod | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/one-pod.log) |
| cross-site-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/cross-site-sharded.log) |
| init-deploy | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/init-deploy.log) |
| upgrade-consistency | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/upgrade-consistency.log) |
| storage | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/storage.log) |
| demand-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/demand-backup.log) |
| self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/self-healing-chaos.log) |
| monitoring-2-0 | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/monitoring-2-0.log) |
| limits | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/limits.log) |
| scheduled-backup | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/scheduled-backup.log) |
| scaling | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/scaling.log) |
| operator-self-healing-chaos | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/operator-self-healing-chaos.log) |
| security-context | [passed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/security-context.log) |
| demand-backup-sharded | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/demand-backup-sharded.log) |
| rs-shard-migration | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/rs-shard-migration.log) |
| arbiter | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/arbiter.log) |
| upgrade | [failed](https://percona-jenkins-artifactory-public.s3.amazonaws.com/cloud-psmdb-operator/PR-1068/22e9e4d1/upgrade.log) |
| We run 17 out of 29|

commit: https://github.com/percona/percona-server-mongodb-operator/pull/1068/commits/22e9e4d175e08657b455aa4d9fef8bafd2d158f4
image: `perconalab/percona-server-mongodb-operator:PR-1068-22e9e4d1`

**Comment by egegunes** [comment]
@pastequo are you willing to work on this further? If you are, I'd be happy to assist you. Otherwise we can take over from here.

I don't think we can include this in v1.14 tough since we already have fairly big changes.

**Comment by pastequo** [comment]
@egegunes I think I can spend time on it, it depends on the size of the changes that you are expecting.I would be happy to help if the amount of changes are reasonable

**Comment by egegunes** [comment]
@pastequo I'm closing this PR due to inactivity. Please re-open it if you want to work on it.

**Pull request closed without merging**
