### PR TITLE
CLOUD-615 automatically cleanup obsolete tests results in PR

### PR DESCRIPTION
**Pull request by delgod**
[CLOUD-615](https://jira.percona.com/browse/CLOUD-615) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)

### CODE REVIEW

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/e47f3f0cf73ba82350e659556fa972c5f55219d4
image: `perconalab/percona-server-mongodb-operator:PR-567-e47f3f0c`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/45c61291669bc07a9d6ad431b515bf2433de7781
image: `perconalab/percona-server-mongodb-operator:PR-567-45c61291`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/d020c9d5975b1b7c238ac4cea85a4834d7e0f84a
image: `perconalab/percona-server-mongodb-operator:PR-567-d020c9d5`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/f8fe3524f543ef0f1df42b2bbaf74b7e6d91e690
image: `perconalab/percona-server-mongodb-operator:PR-567-f8fe3524`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| init-deploy | passed |
| one-pod | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| operator-self-healing | passed |
| security-context | passed |
| rs-shard-migration | passed |
| service-per-pod | passed |
| liveness | passed |
| demand-backup-sharded | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | failed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/c6470366d95e9972f219a59d68ab61954acf92f7
image: `perconalab/percona-server-mongodb-operator:PR-567-c6470366`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| storage | passed |
| one-pod | passed |
| self-healing | passed |
| monitoring-2-0 | passed |
| operator-self-healing | passed |
| arbiter | passed |
| service-per-pod | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| init-deploy | passed |
| users | passed |
| limits | passed |
| data-sharded | passed |
| scaling | passed |
| security-context | passed |
| rs-shard-migration | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/c6470366d95e9972f219a59d68ab61954acf92f7
image: `perconalab/percona-server-mongodb-operator:PR-567-c6470366`

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| one-pod | passed |
| storage | passed |
| init-deploy | passed |
| upgrade-consistency | passed |
| monitoring-2-0 | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| arbiter | passed |
| scheduled-backup | passed |
| security-context | passed |
| operator-self-healing | passed |
| service-per-pod | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| upgrade | passed |
| users | passed |
| upgrade-sharded | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/98a833d862066a5f1818a933a0a52e316e1c7243
image: `perconalab/percona-server-mongodb-operator:PR-567-98a833d8`

**Review by hors — CHANGES_REQUESTED** [review]
Why did you decide to use `us-central1 `? Is it ok to start 9 nodes instead of 3?

**Review by hors — APPROVED** [review]

**Comment by JNKPercona** [comment]
| Test name  | Status |
| ------------- | ------------- |
| init-deploy | passed |
| one-pod | passed |
| storage | passed |
| upgrade-consistency | passed |
| self-healing | passed |
| demand-backup | passed |
| limits | passed |
| scaling | passed |
| scheduled-backup | passed |
| monitoring-2-0 | passed |
| security-context | passed |
| operator-self-healing | passed |
| demand-backup-sharded | passed |
| rs-shard-migration | passed |
| arbiter | passed |
| upgrade | passed |
| service-per-pod | passed |
| upgrade-sharded | passed |
| liveness | passed |
| smart-update | passed |
| version-service | passed |
| users | passed |
| data-sharded | passed |

commit: https://github.com/percona/percona-server-mongodb-operator/pull/567/commits/dbaa4ddf49a2e89bc5cdb7c79e4fed93de9f4a8b
image: `perconalab/percona-server-mongodb-operator:PR-567-dbaa4ddf`

**Review by cap1984 — APPROVED** [review]

**Pull request merged**
